### PR TITLE
Set CoreHost RID to the current RID, not the target RID

### PR DESCRIPTION
**Pull request by ianhays**
Port of https://github.com/dotnet/core-setup/pull/1505 to rel/1.1.0.

resolves https://github.com/dotnet/core-setup/issues/1548

### CODE REVIEW

**Comment by ianhays** [comment]
@gkhanna79 do your new changes to core-setup master remove the need for this PR?

**Comment by gkhanna79** [comment]
This PR needs to be maintained for servicing branch. My changes are only for master as they are more pervasive.

**Comment by ianhays** [comment]
Gotcha, thanks for confirming.

**Comment by gkhanna79** [comment]
@leecow Did you see an email from @ianhays about getting this approved? This change needs to be merged but I cannot find any email in this regard.

**Comment by leecow** [comment]
I'm not finding shiproom mail for this.

**Pull request merged**
