### PR TITLE
Setup clrjit path as property

### PR DESCRIPTION
**Pull request by schellap**
Corresponding PR for https://github.com/dotnet/cli/pull/3231

### CODE REVIEW

**Comment by schellap** [comment]
OSX was validated on the CLI PR. So I am merging:

**Comment by schellap** [comment]
https://github.com/dotnet/cli/pull/3231

**Comment by gkhanna79** [comment]
@schellap Please validate this against release/1.0.0 branch and port the change there as well.

**Comment by schellap** [comment]
> Please validate this against release/1.0.0 branch and port the change there as well

* core-setup hasn't branched.
* cli/rel/1.0.0 already consumes a package with this change. https://github.com/dotnet/cli/pull/3231
* I validated this for servicing and non-servicing as well.

**Pull request merged**
