### PR TITLE
Block X64 Bundle package on X86 OS

### PR DESCRIPTION
**Pull request by rakeshsinghranchi**
Fixes https://github.com/dotnet/core-setup/issues/3123

### CODE REVIEW

**Comment by rakeshsinghranchi** [comment]
Dotnet Core X64 Runtime installer bundle blocks on X86 OS . 

Blocker message : 

**The Microsoft .NET Core Runtime - 2.1.0 Preview 2 (x64) is not supported on x86 operating system. Please install corresponding x86 Installer.**

cc @leecow , @Petermarcu  - PTAL

**Comment by leecow** [comment]
Looks fine. @mairaw for an editorial pass.

**Comment by rakeshsinghranchi** [comment]
Blocker message updated per suggestion.

**Comment by rakeshsinghranchi** [comment]
cc @wli3 for SDK Bundle.

**Pull request merged**
