### PR TITLE
Fix upgrade issue where symbolic link for dotnet-host rpm package gets removed during upgrade

### PR DESCRIPTION
**Pull request by rakeshsinghranchi**
This is the port of fix from master branch. https://github.com/dotnet/core-setup/pull/3467

### CODE REVIEW

**Comment by rakeshsinghranchi** [comment]
@eerhardt  , CI is failing in release/2.0.0 . Is this expected for now?

**Comment by eerhardt** [comment]
> CI is failing in release/2.0.0 . Is this expected for now?

+ @weshaggard @safern 

I believe the release/2.0.0 branch is locked for the 2.0.5 release.

**Comment by weshaggard** [comment]
>I believe the release/2.0.0 branch is locked for the 2.0.5 release.

The branch isn't currently locked, it is open for 2.0.6 release currently. The CI isn't expected to be failing though that should be understood before merging.

**Comment by weshaggard** [comment]
@safern it looks like the pre-release packages aren't published myget, We probably need to do that in order for CI to pass.

**Comment by eerhardt** [comment]
The CI failure is:

```
 Microsoft.NETCore.App depends on Microsoft.Private.CoreFx.NETCoreApp (>= 4.4.4-servicing-26018-01) but Microsoft.Private.CoreFx.NETCoreApp 4.4.4-servicing-26018-01 was not found
```

This is because CoreFX isn't producing this version publicly.

**Comment by weshaggard** [comment]
>This is because CoreFX isn't producing this version publicly.

Exactly that was an internal build.

**Comment by safern** [comment]
> Exactly that was an internal build.

Yes, should we publish those packages or spin a non-stable build from corefx?

**Comment by weshaggard** [comment]
Probably easier to spin a open build of corefx and coreclr, temporarily.

**Comment by safern** [comment]
Ok, taking care of that.

**Comment by safern** [comment]
@dotnet-bot test this

consumed coreclr and corefx.

**Comment by safern** [comment]
@dotnet-bot test this please

corefx and coreclr updated.

**Pull request merged**
