### PR TITLE
Use -fstack-protector when compilng for Linux/ARM

### PR DESCRIPTION
**Pull request by hqueue**
Relate issue: #723 

Let's use -fstack-protector instead of -fstack-protector-strong when using GNU cross
compilers for ARM, since -fstack-protector-strong  is not supported before gcc 4.9.

Signed-off-by: Hyung-Kyu Choi <hk0110.choi@samsung.com>

### CODE REVIEW

**Comment by gkhanna79** [comment]
Is GCC 4.9 not available for us to use so as to not have this conditional?

CC @janvorli

**Comment by janvorli** [comment]
@hqueue we support clang and not gcc. Why are you trying to use gcc instead?

**Comment by hqueue** [comment]
> @hqueue we support clang and not gcc. Why are you trying to use gcc instead?

**Comment by janvorli** [comment]
@hqueue in CoreCLR and CoreFX, we use clang for everything. So I believe we should standardize on clang here as well. @gkhanna79 do you agree with me?

**Comment by hqueue** [comment]
@janvorli I also think using clang is reasonable when considering CoreCLR and CoreFX.

When using clang, there are two ways to cross-compie corehost with ARM header files and libraries.
(1) Using ARM header files and library files from rootfs (which is used to cross-compile CoreCLR for ARM)
(2) Using ARM header files and library files from installed gcc cross toolhain(e.g.  gcc-arm-linux-gnueabihf) from host machine

Becuase corehost is much smaller software compared to CoreCLR, I don't think we really need such heavy rootfs to build corehost. So I prefer 2nd way, using header fils and libaries from installed gcc cross toolchain.

What do you think of it?

**Comment by janvorli** [comment]
@hqueue since CoreCLR and CoreFX use the rootfs, I think we should use the same way to stay consistent. To get the full product, all three repos need to be built, so the rootfs needs to be present on the build machine anyways. We are also planning to have a combined build that would build everything from sources of the three repos together, so consistence is important.

**Comment by hqueue** [comment]
@janvorli I see. Then I think we had better to close this PR, since gcc is not a concern.
And please visit issue #725 and give us any opinion regarding enabling ARM. 

BTW do you have any plan to introduce rootfs for ARM here soon ?

**Comment by gkhanna79** [comment]
I agree with @janvorli that we should have a consistent approach to build the product across the board. This includes the toolset as well. Do we not have a clang based toolset that can be used for cross-compilation instead of GCC?

I am not very familiar with what ROOTFS is used for. Is it about loading the Arm32 emulator and performing the product build within it (and thus, using the toolset within it)?

**Comment by janvorli** [comment]
@gkhanna79 it is not related to the emulator. The rootfs is basically a folder with files that would be on a target machine with the other architectures if you were building it over there. 
So for example, the root level of the rootfs I have generated on my Linux box for ARM cross build looks like this:
```
ls cross/rootfs/arm/
bin  boot  dev  etc  home  lib  media  mnt  opt  proc  root  run  sbin  srv  sys  tmp  usr  var
```

The regular clang it capable of cross compiling. Here is an example of the command line. Please note the `-target armv7-linux-gnueabihf -mthumb -mfpu=vfpv3 --sysroot=/home/janvorli/git/coreclr/cross/rootfs/arm` part:
`/usr/bin/clang++-3.6   -DARM -DBIT64=1 -DBUILDENV_CHECKED=1 -DDEBUG -DDISABLE_CONTRACTS -DLINUX32 -DPIC=1 -DPLATFORM_UNIX=1 -DSystem_Globalization_Native_EXPORTS -DURTBLDENV_FRIENDLY=Checked -D_ARM_ -D_DBG -D_DEBUG  -Wall -Wno-null-conversion -std=c++11 -g -O0 -fPIC -I/home/janvorli/git/coreclr/bin/obj/Linux.arm.Debug/src/corefx/System.Globalization.Native -I/home/janvorli/git/coreclr/src/corefx/System.Globalization.Native -I/home/janvorli/git/coreclr/cross/rootfs/arm/usr/include/arm-linux-gnueabihf    -target armv7-linux-gnueabihf -mthumb -mfpu=vfpv3 --sysroot=/home/janvorli/git/coreclr/cross/rootfs/arm -fno-omit-frame-pointer -fms-extensions -fwrapv -fstack-protector-strong -ferror-limit=4096 -Werror -Wno-unused-private-field -Wno-unused-variable -Wno-microsoft -Wno-tautological-compare -Wno-constant-logical-operand -Wno-unknown-warning-option -Wno-invalid-offsetof -Wno-incompatible-ms-struct -fsigned-char -fPIC -o CMakeFiles/System.Globalization.Native.dir/calendarData.cpp.o -c /home/janvorli/git/coreclr/src/corefx/System.Globalization.Native/calendarData.cpp",
  "file": "/home/janvorli/git/coreclr/src/corefx/System.Globalization.Native/calendarData.cpp`

**Comment by gkhanna79** [comment]
Thank you @janvorli. Do I understand it correct that ROOTFS, in the above example, is being used to invoke the clang compiler that will do a cross-compilation build for arm32? If so, is it not possible to do the same without having ROOTFS (unless ROOTFS is simply being used to have a segregated location for the cross-compilation toolset)?

**Comment by janvorli** [comment]
No, you need the rootfs - it contains e.g. all the target libraries we link to compiled for the target architecture, like ARM.

**Comment by gkhanna79** [comment]
Thanks Jan. 

I agree that ROOTFS approach is the right one to be enabled here as well.

**Pull request closed without merging**
