### PR TITLE
Mark PlatformAbstractions & DependencyModel as stable

### PR DESCRIPTION
**Pull request by wtgodbe**
@weshaggard @safern PTAL

CC @eerhardt

### CODE REVIEW

**Comment by weshaggard** [comment]
@wtgodbe do we need to ship these? IIRC we generally don't stabilize and ship these.

**Comment by wtgodbe** [comment]
We built them for this release because we added Debian9 for the 1.1.10 release - @eerhardt

**Comment by wtgodbe** [comment]
Actually I think I got these mixed up with the host* packages, we may not need this - looking

**Comment by wtgodbe** [comment]
Ah yeah this is the wrong change, what I need to do is revert https://github.com/dotnet/core-setup/commit/51107bf988797510f8221a0a58fb57fac8be4210#diff-dc55be7422231765e25bc0b6326acbd2. Closing.

**Pull request closed without merging**
