### PR TITLE
Enable building upgradeable linux packages with updated runtime-deps dependency moved from host to runtime package

### PR DESCRIPTION
**Pull request by rakeshsinghranchi**
This enables producing upgradeable major.minor installers for Linux. This enables acquiring latest major.minor.release packages using Linux package managers. 

For 2.1 release , these are the package names: 
**dotnet-host**
**dotnet-runtime-deps-2.1**
**dotnet-hostfxr-2.1**
       --depends on dotnet-host (>= major.minor.patch-revision)
**dotnet-runtime-2.1**
    --depends on dotnet-hostfxr-2.1 (>= major.minor.patch-revision)
    -- depends on dotnet-runtime-deps-2.1 (>= major.minor.patch-revision)

This PR takes care of the following : 
1. Updating runtime-deps dependency from dotnet-host to dotnet-runtime package
2. Produce upgradeable Debs and RPMs for Runtime. 
3. Build will continue to produce the old style packages for now. Switching to major upgradeable package will be done later. @leecow  has more details

### CODE REVIEW

**Comment by rakeshsinghranchi** [comment]
cc @Petermarcu @leecow

**Comment by rakeshsinghranchi** [comment]
cc @wli3 @JunTaoLuo

**Comment by JunTaoLuo** [comment]
Hmm so we need to update how our installer works as well right? Which milestone is this work being planned for?

**Comment by leecow** [comment]
@JunTaoLuo - I'm going to schedule a meeting for Monday to discuss the rollout plan for these updated packages. Packages produced from this PR will be built side-by-side with the existing packages so won't break the current processes.

**Pull request merged**
