### PR TITLE
Move NETStandard.Library dependency to Arcade

### PR DESCRIPTION
**Pull request by mmitche**
- Please add a description for changes you are making.
- If there is an issue related to this PR, please add a reference to it.
- If this PR should not run tests please add say skip_ci_please in this description replacing the underscores with spaces.

### CODE REVIEW

**Comment by mmitche** [comment]
Also created a corresponding subscription.  Depends on PR by @rakeshsinghranchi that moves to Arcade since master does not currently import the Versions.props file yet.

**Comment by wtgodbe** [comment]
> error NU1604: Project dependency NETStandard.Library does not contain an inclusive lower bound. Include a lower bound in the dependency version to ensure consistent restore results.

Do we need to make some change to the .pkgproj for NetStandard.Library to get around this?

**Comment by mmitche** [comment]
Yeah this requires the move to arcade so that the Versions.props file is imported.

**Comment by mmitche** [comment]
https://github.com/dotnet/core-setup/tree/dependency-uptake

**Pull request closed without merging**
