### PR TITLE
remove version info from apphost.exe

### PR DESCRIPTION
**Pull request by ramarag**
fixes https://github.com/dotnet/core-setup/issues/1871

@gkhanna79 PTAL

### CODE REVIEW

**Comment by gkhanna79** [comment]
Overall, looks fine. What does the Details tab look like after this change?

**Comment by ramarag** [comment]
oops forgot to add
image

**Comment by gkhanna79** [comment]
LGTM.

@leecow @morganbr Are you fine with this as well (since apphost.exe is supposed to be used for standalone scenarios representing external apps)?

**Comment by morganbr** [comment]
Does publishing the app fill in any of those details? I agree that they shouldn't say this is apphost.exe by Microsoft, but it should ideally match the app in some way.

**Comment by ramarag** [comment]
The default[or any] publishing mechanism in cli does not populate any of the above fields
@dsplaisted for confirmation

**Comment by gkhanna79** [comment]
No, there is no CLI support for it. It can be looked into for the next release, if deemed necessary. FWIW, it never did in the past as well (when dotnet.exe was used as the host).

**Comment by morganbr** [comment]
Doing it in the future sounds fine. It just occurs to me that this doesn't really leave a way (other than postprocessing) for apps to differentiate themselves. That would be more of a problem if administrators want to block a particular standalone .NET Core app without blocking all of them.

**Comment by gkhanna79** [comment]
> this doesn't really leave a way (other than postprocessing) for apps to differentiate themselves. 

While I agree, this has not changed from prior releases. @ramarag Can you please file a CLI (or SDK) future issue to get this information added?

**Comment by leecow** [comment]
I'm fine with the change and looking into enabling support in in the CLI.

**Pull request merged**
