### PR TITLE
Enable Windows ARM64 CI PR builds

### PR DESCRIPTION
**Pull request by sdmaclea**
@dotnet-bot test ci please

### CODE REVIEW

**Comment by sdmaclea** [comment]
@dotnet-bot test ci please

**Comment by sdmaclea** [comment]
@dotnet-bot test Windows_NT arm64 Debug Build

**Comment by sdmaclea** [comment]
This doesn't work without #4835, moving to that PR

**Comment by sdmaclea** [comment]
I had trouble finding the correct label to get the build to have the correct dependencies.  This ended up blocking #4835 so moving it back.

**Comment by sdmaclea** [comment]
@dotnet-bot test ci please

**Comment by wtgodbe** [comment]
So basically we no-longer have to special-case arm64? If so, LGTM

**Comment by sdmaclea** [comment]
@wtgodbe The build is not succeeding, because the build dependencies seem to be missing.  In particular the x64_arm64 compilers.  I thought I could switch to using the same machines as coreclr/corefz, but so far had no success even manually specifying the required label.

**Comment by sdmaclea** [comment]
@mmitche @wtgodbe I tried manually editing the label for the generated win-arm64 Jenkins job to match the label on the coreclr job.

It ran on 
Windows.10.Amd64.ClientRS4.DevEx.Open-1206123609120-0 (a00023L) (Windows.10.Amd64.ClientRS4.DevEx.Open)

It errored with 

```
12:39:40   Calling "D:\j\workspace\debug_windows---c68d094c\src\corehost\Windows\gen-buildsys-win.bat D:\j\workspace\debug_windows---c68d094c\ "15 2017" arm64 e1381f04400d42e4fec7d6a16f2ccedf06647258 3.0.0-preview-27206-0 3.0.0-preview-27206-0 3.0.0-preview-27206-0 3.0.0-preview-27206-0"
12:39:40   "Computed RID for native build is win-arm64"
12:39:48   CMake is a pre-requisite to build this repository but it was not found on the path. Please install CMake from http://www.cmake.org/download/ and ensure it is on your path.
```

How do I make sure to select the right machines with the correct prerequisites (cmake >= 3.10, vs x86_arm64 compiler, arm64 sdk) to cross build win-arm64.

@BruceForstall in case you also might know...

**Comment by mmitche** [comment]
@MattGal Do the DevEx queues have a full VS installation including arm64 on them?

**Comment by BruceForstall** [comment]
I see, for instance:

https://ci.dot.net/job/dotnet_coreclr/job/master/job/arm64_cross_checked_windows_nt_innerloop_prtest/2726/consoleFull

succeeds and uses:

```
Building remotely on Windows.10.Amd64.ClientRS4.DevEx.Open-1205235848986-0 (a00023P) (Windows.10.Amd64.ClientRS4.DevEx.Open) in workspace D:\j\workspace\arm64_cross_c---f1ec3c8e
```

which looks like the same machines?

**Comment by sdmaclea** [comment]
Looks like src/corehost/Windows/probe-win.ps1 does not support cmake > 3.5.  The coreclr version (src/pal/tools/set-cmake-path.ps1) looks more up to date.

**Comment by BruceForstall** [comment]
Maybe you should pick up the dotnet/corefx version at src\Native\Windows\probe-win.ps1, which I recently had to fix/improve (and I didn't move the change back to coreclr).

**Comment by MattGal** [comment]
@mmitche  : I chatted with @Chulhul about this issue and these workloads should be installed on that image:
```
Microsoft.VisualStudio.Component.Windows10SDK.16299.Desktop.arm
Microsoft.VisualStudio.Component.VC.Tools.ARM
Microsoft.VisualStudio.Component.VC.Tools.ARM64
```
If you need more components than that, you can open a core-eng issue describing which queues we need for this, with the names coming from here:
https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-enterprise?view=vs-2017

**Comment by sdmaclea** [comment]
@dotnet-bot test ci please

**Comment by sdmaclea** [comment]
@dotnet-bot test ci please

**Pull request merged**
