### PR TITLE
Updating min OS version

### PR DESCRIPTION
**Pull request by Petermarcu**

### CODE REVIEW

**Comment by rakeshsinghranchi** [comment]
cc @leecow 

LGTM.Thanks. I presume this needs to reflect in pre-requisite document as well : https://docs.microsoft.com/en-us/dotnet/articles/core/macos-prerequisites

**Comment by leecow** [comment]
@rakeshsinghranchi yes, docs will need to be updated for 2.0 dependency changes. 

/cc @mairaw

**Comment by eerhardt** [comment]
LGTM.  Does this need to be ported to `release/2.0.0`?

**Comment by mairaw** [comment]
I've opened https://github.com/dotnet/docs/issues/2492 for the doc work. Is the requirement to have OpenSSL dropped with .NET Core 2.0 as well?

**Pull request closed without merging**
