### PR TITLE
Do not add MSTestResults in armel builds

### PR DESCRIPTION
**Pull request by jyoungyun**
Fixed Tizen armel Release CI failed issue

/cc @gkhanna79

### CODE REVIEW

**Comment by gkhanna79** [comment]
@jyoungyun Please see the CI failure.

**Comment by jyoungyun** [comment]
@gkhanna79 Yes, I know. After merging this PR, the Tizen CI failed issue is resolved. The netci.groovy script is not applied in this CI test.
@dotnet-bot test Windows_NT x64 Release Build please

**Comment by gkhanna79** [comment]
@jyoungyun Can this be merged in that case?

**Comment by jyoungyun** [comment]
@gkhanna79 Yes, it should be merged.

**Comment by gkhanna79** [comment]
@jyoungyun Can you please prepare a PR to port this to release/2.0.0 branch as well and CC me on it?

**Pull request merged**
