### PR TITLE
Add version information to hostfxr component

### PR DESCRIPTION
**Pull request by schellap**
Port of #452

### CODE REVIEW

**Comment by schellap** [comment]
Fixes #444, blocked on #452

**Comment by gkhanna79** [comment]
LGTM - please hold off on the merge though.

**Comment by gkhanna79** [comment]
@schellap Can you please send email to shiproom about this to get this change merged?

**Comment by schellap** [comment]
@gkhanna79 why should this be ported, is this a reason to service it? This is similar to the installer change we talked about.

**Comment by schellap** [comment]
> Why should this be ported

So new releases of hostfxr don't do unversioned installations. So this change is more for safety of future packages.

**Pull request merged**
