### PR TITLE
Update dependencies to latest

### PR DESCRIPTION
**Pull request by karajas**
/cc @gkhanna79 @eerhardt @chcosta @dagood @weshaggard

### CODE REVIEW

**Comment by karajas** [comment]
Any idea why these 2 tests are failing?

``
Microsoft.DotNet.Tools.Publish.Tests.GivenThatICareAboutDotnetTestXunitScenarios.Muxer_activation_of_dotnet_test_XUnit_on_Standalone_Test_App_Succeeds

Microsoft.DotNet.CoreSetup.Test.HostActivation.StandaloneApp.GivenThatICareAboutStandaloneAppActivation.Running_Build_Output_Standalone_EXE_with_DepsJson_and_RuntimeConfig_Local_Succeeds 
```

**Comment by gkhanna79** [comment]
They are both failing with "Failed to initialize CoreCLR", so something unique to them is off. Are you not able to repro these failures locally?

**Comment by karajas** [comment]
I'm able to repro them, I'll poke around.

**Comment by karajas** [comment]
@gkhanna79 So with @erictj help, we seemed to have found that the test failures are from a missing System.Private.CoreLib.ni.dll which breaks the dev "run from packages" scenario, which blocks the merge.

**Comment by ericstj** [comment]
@gkhanna79 it looks like you removed CoreLib from the native folder with https://github.com/dotnet/coreclr/commit/c983bb86ddf46916206efc7cd5bc942ec8b834cb#diff-879a1a862afbe14d9c6b5b2973c652a2.  Now coreclr is failing to activate when trying to run from packages (build of standalone app).  If you want to remove corelib from native you may need to teach CLR how to find it using the paths that the host sets up for TPA list...

**Comment by gkhanna79** [comment]
I chatted with @karajas and suggested he go ahead with your workaround above to unblock his PR and ensure the package carries the correct asset. 

@karajas will also file an issue against me and I will look into fixing this so that path to CoreLib can be specified explicitly instead of expecting it to be next to CoreCLR.dll.

CC @jkotas

**Comment by chcosta** [comment]
If we're going to have a fix available tomorrow, there's nothing terribly pressing at the moment that would require a workaround to get this PR in.

**Comment by gkhanna79** [comment]
@karajas will have a fix in tonight so that PR will be unblocked. I expect to have a fix in CoreCLR tonight or tomorrow and once that propagates over to Core-Setup, will undo the workaround.

We should get things going.

**Comment by gkhanna79** [comment]
@karajas https://devdiv.visualstudio.com/DevDiv/_Build/explorer?_a=summary&buildId=719817 build successfully completed, so you should be able to pickup CoreCLR from this and not require the workaround.

**Comment by karajas** [comment]
I have a passing local build so will wait for CI.

**Comment by gkhanna79** [comment]
@karajas Looks like this will be green. Can you please merge it once green so that I can validate https://github.com/dotnet/core-setup/pull/2272 against your changes?

**Comment by gkhanna79** [comment]
@dotnet-bot test Fedora24 x64 Debug Build please

**Comment by gkhanna79** [comment]
@dotnet-bot test OpenSUSE42.1 x64 Debug Build  please

**Comment by gkhanna79** [comment]
OpenSuse 42.1 failed because of the following:

`Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Collections.NonGeneric, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified. at System.Security.Cryptography.X509Certificates.X509ChainPolicy.Reset() at System.Security.Cryptography.X509Certificates.X509Chain.get_ChainPolicy() at System.Net.Http.CurlHandler.SslProvider.VerifyCertChain(IntPtr storeCtxPtr, IntPtr curlPtr) at Interop.Http.MultiPerform(SafeCurlMultiHandle multiHandle) at System.Net.Http.CurlHandler.MultiAgent.WorkerBodyLoop()`

Log is at https://ci.dot.net/job/dotnet_core-setup/job/master/job/debug_opensuse42.1_x64_prtest/1377/testReport/junit/Microsoft.DotNet.CoreSetup.Test.HostActivation.MultilevelSDKLookup/GivenThatICareAboutMultilevelSDKLookup/SdkLookup_Must_Pick_The_Highest_Semantic_Version/

@weshaggard Is this known?

**Comment by weshaggard** [comment]
>@weshaggard Is this known?

No that isn't known but I also don't see that failing in the current CI runs so perhaps it was some other issue.

**Comment by ericstj** [comment]
> Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Collections.NonGeneric, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. 

> @weshaggard Is this known?

Shouldn't be missing.  That assembly is part of the shared framework.  I double checked the package from corefx and that assembly is present.

**Comment by ericstj** [comment]
Let's see if CI succeeds this time.

Fixes #1960

**Comment by karajas** [comment]
All green, should I merge?

**Comment by gkhanna79** [comment]
I am not aware of any reason to not - @ericstj @weshaggard ?

**Pull request merged**
