### PR TITLE
Add CI support for PortableLinux build

### PR DESCRIPTION
**Pull request by gkhanna79**
Opened new PR for this @mmitche

### CODE REVIEW

**Comment by gkhanna79** [comment]
@dotnet-bot test ci please

**Comment by gkhanna79** [comment]
I have validated that the new leg works as expected at https://ci.dot.net/job/dotnet_core-setup/job/master/job/GenPRTest/job/release_portablelinux_x64_prtest/2/consoleFull.

@mmitche @ramarag @ellismg PTAL

**Comment by ellismg** [comment]
LGTM

**Comment by mmitche** [comment]
@gkhanna79 Your change of the os variable to RHEL when it's portable linux meant that the github trigger was set up to report to GitHub as "RHEL 7.2" instead of the portable linux build.  So GitHub simply updated the RHEL status twice.

**Comment by gkhanna79** [comment]
@mmitche It seems to me that the multiple entries for Windows should result in the same behaviour but they do not. Why is that? 

PortableLinux builds need to execute on RHEL7.2 but reported as PortableLinux. What would be the correct way to do so?

**Comment by gkhanna79** [comment]
Would special casing https://github.com/dotnet/core-setup/pull/1310/files#diff-2d212ad84506951c8f928e21aed24580R76 (where trigger is created), to specify "PortableLinux" for  OS, address the problem?

**Comment by mmitche** [comment]
Ya, https://github.com/dotnet/core-setup/pull/1310/files#diff-2d212ad84506951c8f928e21aed24580R51 causes https://github.com/dotnet/core-setup/pull/1310/files#diff-2d212ad84506951c8f928e21aed24580L70 to overlap for Portable and RHEL

**Comment by gkhanna79** [comment]
Ok - I have pushed a PR with the fix at https://github.com/dotnet/core-setup/pull/1324. Can you PTAL?

**Pull request merged**
