### PR TITLE
Adding FilesToSign error check to all ItemGroups

### PR DESCRIPTION
**Pull request by jcagme**
This error check was added to only one item group. Adding it to all

### CODE REVIEW

**Comment by weshaggard** [comment]
Lets wait until after the current servicing is done before merging.

**Comment by jcagme** [comment]
Changes will be merged until we have stable builds in place. We don't want extra builds being triggered and using the only two agent machines we have in the pool we use for signing just for this change.

**Comment by eerhardt** [comment]
Can this PR be merged now?

**Comment by weshaggard** [comment]
Yes :)

**Pull request merged**
