### PR TITLE
Stop building Linux Mint packages

### PR DESCRIPTION
**Pull request by rakeshsinghranchi**
Fixes https://github.com/dotnet/core-setup/issues/3980

### CODE REVIEW

**Comment by Petermarcu** [comment]
Are there links and other things that need to be fixed up with this change? I think we link to them on the readme for example.

**Comment by Petermarcu** [comment]
I don't think we need this in Preview2 but yes, we need to make sure it gets into release/2.1 right after that.

**Comment by rakeshsinghranchi** [comment]
> Are there links and other things that need to be fixed up with this change? I think we link to them on the readme for example.
No, Linux Mint packages are not in Readme page. 
>I don't think we need this in Preview2 but yes, we need to make sure it gets into release/2.1 right after that.
Labelled this issue as post-ZBB for 2.1.0 milestone. @leecow  suggested it will be taken care of porting from master to release/2.1 branch as centralized effort for all post-ZBB fixes .

**Comment by Petermarcu** [comment]
yeah, it should flow to release automatically. I see links to these packages for prodcon: https://github.com/dotnet/versions/tree/master/build-info/dotnet/product/cli/release/2.1

I don't know where those come from, we can probably just delete those rows.

**Comment by rakeshsinghranchi** [comment]
Looking at the history for readme file,it looks like readme file is regenerated with every build.If it is auto-generated, assumption is that it is auto-deleted once removed from core-setup. 

 @dagood can confirm.

**Comment by Petermarcu** [comment]
Yeah, I just made a PR to drop the mint rows. Dont worry about that one.

**Comment by Petermarcu** [comment]
This is unrelated to the Tizen build so I'm going to merge.

**Pull request merged**
