### PR TITLE
Add CI support for PortableLinux build

### PR DESCRIPTION
**Pull request by gkhanna79**
skip ci please

### CODE REVIEW

**Comment by gkhanna79** [comment]
@dotnet-bot test ci please

**Comment by gkhanna79** [comment]
@mmitche PTAL - this adds support for a CI leg to run on RHEL7.2 for portableLinux build. Can you tell me how to trigger CI testing as the command above didn't trigger it?

FYI @janvorli

**Comment by gkhanna79** [comment]
CC @ramarag @wtgodbe

**Comment by mmitche** [comment]
@gkhanna79 Adding skip ci please causes it to ignore future comments (admittedly that's not really what we want).

**Pull request closed without merging**
