### PR TITLE
Remove host RPM postinstall, install the symlink

### PR DESCRIPTION
**Pull request by dagood**
Rather than using postinstall and postuninstall scripts to maintain a /usr/bin/dotnet symlink, have the RPM package install the symlink file itself. This reduces the complexity of the host package.

Inspired by https://github.com/dotnet/core-setup/issues/5221.

Manual testing: built the RPMs, ran `dnf install *` in a `fedora:28` container, and saw that `dotnet --info` still worked.

### CODE REVIEW

**Comment by omajid** [comment]
I am not familiar enough with the code to review it, but I can say that using plain files instead of rpm scriptlets is definitely the right approach.

**Comment by dagood** [comment]
I played some more with this, and found an interesting behavior although I don't know if we need to be concerned about it:

```
#> dnf install host-plain-symlink.rpm
...
#> ls -l /usr/bin/dotnet
/usr/bin/dotnet -> /usr/share/dotnet/dotnet
#> dnf reinstall host-using-scriptlets.rpm
...
Running transaction
  Preparing        :                                              
  Reinstalling     : dotnet-host-3.0.0-0.1.preview4_27507_0.x86_64
  Running scriptlet: dotnet-host-3.0.0-0.1.preview4_27507_0.x86_64
Creating dotnet host symbolic link: /usr/bin/dotnet
  Erasing          : dotnet-host-3.0.0-0.1.preview4_27507_0.x86_64
  Verifying        : dotnet-host-3.0.0-0.1.preview4_27507_0.x86_64
  Verifying        : dotnet-host-3.0.0-0.1.preview4_27507_0.x86_64
...
#> ls -l /usr/bin/dotnet
No such file or directory!
```

This emulates (I believe) having an RPM installed with this PR's change, then downgrading to an RPM that still uses the scriptlets. I.e. if someone tries to downgrade their host package from an RPM with this change to one without it, the symlink would disappear.

This seems to be caused by the operation ordering for upgrades. (https://docs.fedoraproject.org/en-US/packaging-guidelines/Scriptlets/#_ordering) It's harder to see above because the package identities are identical, but the scriptlet package's postinstall is running, *then* the old package is erased. The old package "owns" `/usr/bin/dotnet` and the new one doesn't, so the symlink is deleted.

Reinstalling the scriptlet package again fixes the symlink.

On the other hand, I wasn't able to find any issues going from the scriptlet package to the symlink file package, which would be the normal upgrade scenario.

Options I see:
1. If we port this change to 2.1 and 2.2, downgrades to new servicing releases will work because they'll "own" this file too.
2. It looks like we could protect against this by adding a postuninstall scriptlet to the new package that makes sure the symlink is still there in upgrade scenarios. (I don't like this, makes things even more complicated.)
3. Don't try to support downgrade.
4. Don't take this fix. (Keep using scriptlets. 😞)

@leecow do we care about host RPM downgrades?

**Comment by leecow** [comment]
Porting the work to 2.1 and 2.2 would mitigate most of this. Someone could still hit it if they really needed to install a specific patch version from the past but I think we can document our way around that.

**Comment by dagood** [comment]
Cool. This ports without conflicts to `release/2.1` (and 2.2), so does this look ok to merge to you, @leecow?

**Comment by leecow** [comment]
Yes, for 3.0. Let's raise it in shiproom next week as an FYI before merging into 2.1/2.2.

**Pull request merged**
