### PR TITLE
Handle --configuration in src/corehost/build.sh correctly

### PR DESCRIPTION
**Pull request by omajid**
Currently, the value of the configuration is ignored.

### CODE REVIEW

**Comment by omajid** [comment]
@dotnet-bot test armel Release please

**Comment by omajid** [comment]
@dotnet-bot test Tizen armel Release please

**Comment by omajid** [comment]
@dotnet-bot test this please

**Comment by dagood** [comment]
/cc @weshaggard 

(Tizen leg failures are a known issue and can be ignored: https://github.com/dotnet/corefx/issues/28901.)

**Comment by omajid** [comment]
Can someone please merge this?

**Comment by dagood** [comment]
FYI @eerhardt

**Pull request merged**
