### PR TITLE
Merge commit master 'ba0f145' into release/2.0.0

### PR DESCRIPTION
**Pull request by weshaggard**
cc @gkhanna79 @eerhardt

### CODE REVIEW

**Comment by eerhardt** [comment]
A bunch of the .sh files are getting their permissions changed.  We don't want this:

`scripts/arm32_ci_script.sh → tools-local/scripts/arm32_ci_script.sh 100755 → 100644`

**Comment by weshaggard** [comment]
>A bunch of the .sh files are getting their permissions changed. We don't want this:

Fixed with https://github.com/dotnet/core-setup/pull/2427/commits/dc1240d663a2b0ec7b8b2d21962d885afc8de82e

**Comment by eerhardt** [comment]
Getting a seg fault during crossgen of the Tools folder on PortableLinux x64. 

```
Tools/crossgen.sh: line 54: 33824 Segmentation fault      (core dumped) $__crossgen /Platform_Assemblies_Paths $__sharedFxDir:$__toolsDir /nologo /MissingDependenciesOK /ReadyToRun $__file > /dev/null 
 ```

Also the win x86 leg failed with a unrecognized build option:

```
10:18:20 Done initializing tools.
10:18:20 Error: Unexpected qualifier: -Configuration.
10:18:20 Our dev workflow has changed! Use -? for help in the new options we have and how to pass parameters now.
10:18:21 Build step 'Execute Windows batch command' marked build as failure
```

I'm going to close and re-open to see if that fixes it.

**Comment by weshaggard** [comment]
@dotnet-bot test this please

**Pull request merged**
