### PR TITLE
Removing Company Info from apphost.exe

### PR DESCRIPTION
**Pull request by ramarag**
This removes the mention of microsoft in the binary details

@gkhanna79 @eerhardt PTAL

### CODE REVIEW

**Comment by ramarag** [comment]
After this change AppHost's properties will look like : 

image

**Comment by gkhanna79** [comment]
Can we also cleanup the Description, File Version and Product version @ramarag?

**Comment by ramarag** [comment]
@gkhanna79 i would keep them, why do you think we should strip them off ?

**Comment by gkhanna79** [comment]
They are reflective of our build and have no semblence to the app in which apphost will be used for. Thus, it will be good to clear them out.

**Comment by gkhanna79** [comment]
We should get this in for Preview1 build. @ramarag can we get this in by early next week?

**Comment by ramarag** [comment]
@gkhanna79 i believe the information we have left in the binary will help us trouble shoot when and if we ship another version of apphost.exe, I understand we never want to change, but we should allow for them to be easily distinguishable

**Comment by gkhanna79** [comment]
I believe we can determine the version based upon the toolset used to build the application or the .NET Core App that is targeted. From an end-user perspective, we really do not want to have any such information, to avoid the case of multiple standalone hosts having the same information that could confuse locked down scenarios from locking all of them when they intended to lock down just one.

**Comment by ramarag** [comment]
closing this as versioning tooling might change with @chcosta' changes

**Pull request closed without merging**
