### PR TITLE
Updating CoreClr to preview1-24513-02

### PR DESCRIPTION
**Pull request by dagood**
I ripped out the corefx build-info dependency, ran update-dependencies.ps1, and cleaned up.

/cc @wtgodbe @brthor @gkhanna79

### CODE REVIEW

**Comment by wtgodbe** [comment]
Awesome, thanks! Let's merge once the CI is green

**Comment by brthor** [comment]
:shipit:

**Comment by gkhanna79** [comment]
LGTM

**Comment by wtgodbe** [comment]
https://devdiv.visualstudio.com/DevDiv/Net%20CoreFX/_build/explorer?_a=summary&buildId=330375 - here's the core-setup 1.1.0 pipebuild that just got triggered by this PR being merged

**Comment by gkhanna79** [comment]
Great! @wtgodbe @dagood Please keep an eye on this build. Assuming it goes through clean, @wtgodbe can you please queue a new CoreCLR pipeline build to get the E2E flow tested?

**Pull request merged**
