### PR TITLE
Fixes to build against NETCoreApp1.1.

### PR DESCRIPTION
**Pull request by gkhanna79**
CC @weshaggard

### CODE REVIEW

**Comment by gkhanna79** [comment]
@weshaggard @dagood @mellinoe We have a green CI with changes from @weshaggard and my fixes for lower-case fixes.

@mellinoe Do you need to perform any validations for the CLI for the new distros?

**Comment by mellinoe** [comment]
> Do you need to perform any validations for the CLI for the new distros?

The CI is turned on for Ubuntu 16.10 and openSUSE 42.1, and Fedora 24 isn't actually ported over to master yet. I'm working on that now and will make sure that it works with this change (I need to upload a version to azure for it).

**Comment by gkhanna79** [comment]
In that case, any concerns if I go ahead and merge this change @weshaggard ?

**Comment by weshaggard** [comment]
@mellinoe did you upload the manually created CLI for the new distro's? Otherwise I don't know how they are passing in CI.

**Comment by gkhanna79** [comment]
Merging on behalf @weshaggard for netcoreapp1.1 changes, alongwith my fixes to handle lower-case nuget restores.

**Pull request merged**
