### PR TITLE
Update CoreClr version to servicing for 1.0.13

### PR DESCRIPTION
**Pull request by wtgodbe**
CC @weshaggard, @safern 

Need to merge this before queuing servicing build for core-setup 1.1.0

### CODE REVIEW

**Comment by safern** [comment]
@wtgodbe I suspect you already updated the other places where CoreCLR dependency needs to be updated for 1.1.0

**Comment by safern** [comment]
I see this PR is doing that: https://github.com/dotnet/core-setup/pull/3833/files

Just make sure that one is merged before queuing your build.

**Comment by wtgodbe** [comment]
@dotnet-bot test this please

**Comment by weshaggard** [comment]
I think I would include this with https://github.com/dotnet/core-setup/pull/3868

**Pull request closed without merging**
