### PR TITLE
Validate if ${TMPDIR} is pointing to a directory in Unix systems

### PR DESCRIPTION
**Pull request by lpereira**
While not an actual fix for #4149, this adds a little bit of robustness when trying to determine the path to a temporary directory.

(is_directory() isn't called for /var/tmp and /tmp because the full path qualifier, including the trailing slash, are also passed to realpath(), which should take care of this check.)

### CODE REVIEW

**Comment by dagood** [comment]
@janvorli @lpereira @vitek-karas Can some review this and get it merged?

**Review by janvorli — APPROVED** [review]
LGTM, thank you!

**Comment by ViktorHofer** [comment]
What's the status here?

**Comment by ViktorHofer** [comment]
OK just saw that this issue has the post-consolidation label. Sorry for the noise.

**Comment by maryamariyan** [comment]
Thank you for your contribution. As announced in #27549 the dotnet/runtime repository will be used going forward for changes to this code base. Closing this PR as no more changes will be accepted into master for this repository. If you’d like to continue working on this change please move it to dotnet/runtime.

**Pull request closed without merging**
