### PR TITLE
Use new version of CLI so we can get working CLI for OpenSUSE

### PR DESCRIPTION
**Pull request by wtgodbe**
Should fix the build break in our pipelines.

### CODE REVIEW

**Comment by wtgodbe** [comment]
CC @gkhanna79 @mellinoe @brthor 

Eric - feel free to merge this after CI is green & the new CLIs are up (or just ping me)

**Comment by mellinoe** [comment]
Why did you remove `-Channel Sdk` ?

**Comment by wtgodbe** [comment]
@mellinoe, According to a conversation I had with @brthor yesterday, the version string is sufficient as a key (as opposed to in the past & in 1.0.0, when we needed both a version AND a channel to comprise a key). So `-Channel Sdk` was redundant, since I was already specifying the version (correct me if I'm wrong here, Bryan).

**Comment by brthor** [comment]
@mellinoe in the `rel/1.0.0` version of the install scripts, channel and version are independent concepts, and you don't need both.

in the `rel/1.0.0-preview2` of the install scripts that isn't true though.

**Comment by mellinoe** [comment]
Ok, sounds good. The right thing is getting downloaded in CI, so this LGTM.

**Comment by wtgodbe** [comment]
https://devdiv.visualstudio.com/DevDiv/Net%20CoreFX/_build/explorer?_a=summary&buildId=366482 here's the triggered core-setup build

**Pull request merged**
