### PR TITLE
Pass CrossBuild correctly to get linux Arm build.

### PR DESCRIPTION
**Pull request by gkhanna79**
This is non-build definition part to fix https://github.com/dotnet/core-setup/issues/2280.

I have confirmed that with this change, produced binaries are ELF32 ARMHF.

@eerhardt PTAL

### CODE REVIEW

**Comment by ellismg** [comment]
This is probably not going to play nicely with my PR.

**Comment by gkhanna79** [comment]
I will fix this once your PR is merged @ellismg

**Comment by gkhanna79** [comment]
@ellismg When do you expect to have your PR merged as I would like to get Arm binaries working soon?

**Comment by eerhardt** [comment]
I'll review when the changes are rebased on @ellismg's PR.  But this looks simple enough, so dont' let my review block you.

**Comment by gkhanna79** [comment]
@dotnet-bot test Ubuntu16.04 x64 Release Build please

**Comment by gkhanna79** [comment]
@dotnet-bot test PortableLinux x64 Release Build  please

**Comment by gkhanna79** [comment]
@eerhardt @ellismg This has been rebased over Matt's PR.

**Comment by gkhanna79** [comment]
@dotnet-bot test ci please

**Pull request merged**
