### PR TITLE
Fix potential type issue identified by warning

### PR DESCRIPTION
**Pull request by schellap**
@gkhanna79 PTAL.

### CODE REVIEW

**Comment by gkhanna79** [comment]
Failing with the following:

16:15:14   d:\j\workspace\debug_windows---b57b94ba\src\corehost\common\utils.cpp(145): error C2065: 'ssize_t': undeclared identifier [D:\j\workspace\debug_windows---b57b94ba\artifacts\win81-x86\corehost\cmake\cli\dll\hostpolicy.vcxproj]
16:15:14   d:\j\workspace\debug_windows---b57b94ba\src\corehost\common\utils.cpp(145): error C2146: syntax error: missing ';' before identifier 'pos' [D:\j\workspace\debug_windows---b57b94ba\artifacts\win81-x86\corehost\cmake\cli\dll\hostpolicy.vcxproj]
16:15:14   d:\j\workspace\debug_windows---b57b94ba\src\corehost\common\utils.cpp(145): error C2065: 'pos': undeclared identifier [D:\j\workspace\debug_windows---b57b94ba\artifacts\win81-x86\corehost\cmake\cli\dll\hostpolicy.vcxproj]
16:15:14   d:\j\workspace\debug_windows---b57b94ba\src\corehost\common\utils.cpp(145): error C2146: syntax error: missing ';' before identifier 'path_sep' [D:\j\workspace\debug_windows---b57b94ba\artifacts\win81-x86\corehost\cmake\cli\dll\hostpolicy.vcxproj]
16:15:14   d:\j\workspace\debug_windows---b57b94ba\src\corehost\common\utils.cpp(146): error C2065: 'pos': undeclared identifier [D:\j\workspace\debug_windows---b57b94ba\artifacts\win81-x86\corehost\cmake\cli\dll\hostpolicy.vcxproj]
16:15:14   d:\j\workspace\debug_windows---b57b94ba\src\corehost\common\utils.cpp(148): error C2065: 'pos': undeclared identifier [D:\j\workspace\debug_windows---b57b94ba\artifacts\win81-x86\corehost\cmake\cli\dll\hostpolicy.vcxproj]
16:15:14   d:\j\workspace\debug_windows---b57b94ba\src\corehost\common\utils.cpp(150): error C2065: 'pos': undeclared identifier [D:\j\workspace\debug_windows---b57b94ba\artifacts\win81-x86\corehost\cmake\cli\dll\hostpolicy.vcxproj]
16:15:14 
16:15:14     0 Warning(s)
16:15:14     21 Error(s)

**Comment by schellap** [comment]
ssize_t is POSIX, I'll just use int.

**Comment by gkhanna79** [comment]
LGTM.

**Comment by gkhanna79** [comment]
Please ignore the Windows NT Arm failure.

**Pull request merged**
