### PR TITLE
November update snap yaml

### PR DESCRIPTION
**Pull request by leecow**
yaml updates for November snap builds

### CODE REVIEW

**Review by vivmishra — APPROVED** [review]

**Comment by dagood** [comment]
Wrong repo, this change is going to disappear pretty unceremoniously. 😄

https://github.com/dotnet/runtime/tree/master/src/installer/pkg/packaging/snaps

**Comment by leecow** [comment]
@dagood - so dotnet/runtime == the consolidated repo?

**Comment by dagood** [comment]
Yep, everything that was core-setup is in `src/installer/` in the consolidated `dotnet/runtime` repo.

**Comment by vivmishra** [comment]
@leecow , I will let you port this PR as-is, before I add changes for 3.1.

**Comment by leecow** [comment]
https://github.com/dotnet/runtime/pull/345

**Pull request merged**
