### PR TITLE
Defining Global json roll forward along patch versions behavior.

### PR DESCRIPTION
**Pull request by ghost**
If the version found in the Global json does not exist; roll forward along patch versions.

Addresses: 
https://github.com/dotnet/cli/issues/6688 - Global json roll forward
https://github.com/dotnet/core-setup/issues/2570 - minor BUG fix

1. If global.json does not contain a version, use latest version – consider release & pre-release
    1.1 If nothing can be found -- error out
2. If global.json does contain a version:
    2.1 If the version exists, use that
    2.2 If the version does not exist, use latest **patch** version – consider release & pre-release
    2.3 If nothing can be found -- error out

@dotnet/dotnet-cli

### CODE REVIEW

**Comment by MattGertz** [comment]
@livarcocc Is this for VS or the overlay?

**Comment by Petermarcu** [comment]
@MattGertz, It's in the runtime host so it should be in the "overlay".

**Comment by nguerrera** [comment]
@MattGertz @Petermarcu @livarcocc We also carry this code in VS with the resolver in order to make VS replicate the same behavior vs. global.json as dotnet on the command line.

**Comment by Petermarcu** [comment]
@nguerrera does that code somehow get mirrored? VS doesn't distribute the host binary built from this repo does it? So there would be a different PR for that?

**Comment by MattGertz** [comment]
Yeah, I wondered.  If it touches VS, then that'll need director approval.  @livarcocc Who owns this particular repo?  I'm embarrassed to say that I don't actually know that and am therefore unsure who owns the rollup to JoC.  If it's me, we'll need the right labels so that it will show up in the director queries properly (i.e. "Pending director approval", "Pending Shiproom approval" and "Approved to merge". @Petermarcu is also going to follow up with @nguerrera per the above.

**Comment by MattGertz** [comment]
@Petermarcu clarified the ownership BTW -- it's both of us. :-)  I would roll it up in this case.

**Comment by johnbeisner** [comment]
[RE Making dotnet SDK roll semantics smarter.txt](https://github.com/dotnet/core-setup/files/1053313/RE.Making.dotnet.SDK.roll.semantics.smarter.txt)

**Comment by Petermarcu** [comment]
@MattGertz, Yup, for most cases it me but there is this very small bit of code for how to look up the SDK that is owned by the SDK team.

**Comment by gkhanna79** [comment]
@Petermarcu is correct - the SDK parts of the host are owned by @livarcocc.

**Pull request merged**
