### PR TITLE
Allow missing satellite assemblies (#2717)

### PR DESCRIPTION
**Pull request by steveharter**
@dotnet/dotnet-cli

@Petermarcu for approval

**Customer scenario**
Be able to add a language pack later after the app has been installed, or to avoid deploying a very large (disk size) language pack when it is not necessary. Previously, the satellite assemblies specified in the deps file had to physically exist on disk before the app could run. Now missing satellite assemblies are ignored during startup.

This does not enable a complete 'lightup' scenario because it still requires at least one satellite assembly to be specified in the deps file (to provide a root resource directory), although the assembly does not need to exist on disk.

**Bugs this fixes:**
https://github.com/dotnet/core-setup/issues/2658
Also dotnet/cli#6877 depends on this core-setup change.
Direct port from https://github.com/dotnet/core-setup/pull/2717

**Workarounds, if any**
For each satellite assembly in the deps, have an empty \ dummy satellite assembly on disk (not ideal).

**Risk**
Low. Very targeted to just handle this scenario for resource assemblies only.

**Performance impact**
None.

**Is this a regression from a previous update?**
No

**Root cause analysis:**
The scenario of adding a language pack later or removing one due to disk space was not considered early on.

**How was the bug found?**
Not a bug necessarily, but an enhancement. New scenario(s) per above.

### CODE REVIEW

**Comment by steveharter** [comment]
cc @livarcocc @gkhanna79

**Comment by livarcocc** [comment]
Does you know which version of the preview3 runtime will contain these changes? I was expecting a maestro insertion but we haven't gotten one yet.

**Comment by Petermarcu** [comment]
@weshaggard Do you know why auto pr's may not be happening?

The latest builds should have it so picking up 20170624.01 should do it.

**Comment by weshaggard** [comment]
@Petermarcu they are https://github.com/dotnet/core-setup/pull/2686, but we currently have blocking issues with it.

**Comment by weshaggard** [comment]
@livarcocc reading closer I'm unsure if you are referring to auto-PR's into core-setup or into cli or sdk?

**Comment by livarcocc** [comment]
I mean CLI. We need to pick up a build of core-setup with this fix. But we haven't had a insertion from core-setup into the CLI for a few days now.

**Comment by weshaggard** [comment]
I don't know much about the CLI auto-PR's. @eerhardt is that automated as well or do you do that manually?

**Comment by eerhardt** [comment]
They are automated.

Since I'm out for the next 2 months, I'll do a little teaching, so you guys can self-diagnose these things in the future.

The first thing to always check is that the official build of the upstream repo is publishing a build-info file to dotnet/versions.  So in this case, https://github.com/dotnet/versions/tree/master/build-info/dotnet/core-setup/release/2.0.0 was updated an hour ago.  So yes, new builds are being published.

Next, check the VSTS build definition that does the update and pushes the auto-PR.  To find it, look up the appropriate build def in https://github.com/dotnet/versions/blob/master/Maestro/subscriptions.json.  In this case, we are looking for the subscription that takes core-setup and pushes it to cli/release/2.0.0.  This one: https://github.com/dotnet/versions/blob/master/Maestro/subscriptions.json#L493-L508.  See that the "action" is "cli-dependencies".  Look that action up at the top of the file "actions" list: https://github.com/dotnet/versions/blob/master/Maestro/subscriptions.json#L45-L50.  So this is devdiv.visualstudio.com build def 808.

https://devdiv.visualstudio.com/DevDiv/_build/index?definitionId=808&_a=completed

Go there and see that the build has been failing for days with errors like:

```
2017-06-26T17:48:16.9335446Z ##[error]System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\buildguest\.dotnet\2.1.0-preview1-006567.dotnetFirstUseSentinel'.
   at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.IO.File.Create(String path)
   at Microsoft.Extensions.EnvironmentAbstractions.FileWrapper.CreateEmptyFile(String path)
   at Microsoft.DotNet.Configurer.FirstTimeUseNoticeSentinel.CreateIfNotExists()
   at Microsoft.DotNet.Configurer.DotnetFirstTimeUseConfigurer.PrintFirstTimeUseNotice()
   at Microsoft.DotNet.Configurer.DotnetFirstTimeUseConfigurer.Configure()
   at Microsoft.DotNet.Cli.Program.ConfigureDotNetForFirstTimeUse(INuGetCacheSentinel nugetCacheSentinel, IFirstTimeUseNoticeSentinel firstTimeUseNoticeSentinel, CliFallbackFolderPathCalculator cliFallbackFolderPathCalculator)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
Failed to restore
At D:\a\1\s\build_projects\update-dependencies\update-dependencies.ps1:48 char:27
```

Looks to be a bug in the first run experience when trying to `dotnet restore` for the first time on this box.

I can reproduce this bug with the latest `master` build of the CLI on my machine by deleting any existing `C:\users\eerhardt\.dotnet` folder and calling restore.

```
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\eerhardt\.dotnet\2.1.0-preview1-006567.dotnetFirstUseSentinel'.
   at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.IO.File.Create(String path)
   at Microsoft.Extensions.EnvironmentAbstractions.FileWrapper.CreateEmptyFile(String path)
   at Microsoft.DotNet.Configurer.FirstTimeUseNoticeSentinel.CreateIfNotExists()
   at Microsoft.DotNet.Configurer.DotnetFirstTimeUseConfigurer.PrintFirstTimeUseNotice()
   at Microsoft.DotNet.Configurer.DotnetFirstTimeUseConfigurer.Configure()
   at Microsoft.DotNet.Cli.Program.ConfigureDotNetForFirstTimeUse(INuGetCacheSentinel nugetCacheSentinel, IFirstTimeUseNoticeSentinel firstTimeUseNoticeSentinel, CliFallbackFolderPathCalculator cliFallbackFolderPathCalculator)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
```

**Comment by steveharter** [comment]
@livarcocc will this be fixed with https://github.com/dotnet/cli/pull/6999?

**Comment by livarcocc** [comment]
Correct, this has been fixed in the CLI. Meanwhile, is there a  core-setup build with the fix that I can manually insert into the CLI?

**Comment by Petermarcu** [comment]
Yeah, anything after 20170624.01.

**Pull request merged**
