### PR TITLE
Ask Mode: Create symbols packages, add serviceable attribute, and update assembly info

### PR DESCRIPTION
**Pull request by chcosta**
* Include copyright info, serviceable attribute, and produce symbols
packages for Microsoft.Extensions.DependencyModel and
Microsoft.DotNet.PlatformAbstractions

* Align AssemblyFileVersion with VersionPrefix, remove env vars from dotnet
pack

* Add license files

* small tweak to packagepath

* Add package licenseurl and projecturl

### CODE REVIEW

**Comment by chcosta** [comment]
```
14:54:50 D:\j\workspace\debug_windows---55156150\Tools\dotnetcli\sdk\2.0.0-preview1-005899\NuGet.targets(97,5): error : Unable to obtain lock file access on 'C:\Users\dotnet-bot\AppData\Local\Temp\NuGetScratch\lock\31f4e521d883d8e9d7523dba4604fb7f02a3f352' for operations on 'D:\j\workspace\debug_windows---55156150\packages\microsoft.net.native.compiler\1.6.1\microsoft.net.native.compiler.1.6.1.nupkg'. This may mean that a different user or administator is holding this lock and that this process does not have permission to access it. If no other process is currently performing an operation on this file it may mean that an earlier NuGet process crashed and left an inaccessible lock file, in this case removing the file 'C:\Users\dotnet-bot\AppData\Local\Temp\NuGetScratch\lock\31f4e521d883d8e9d7523dba4604fb7f02a3f352' will allow NuGet to continue. [D:\j\workspace\debug_windows---55156150\src\pkg\projects\Microsoft.NETCore.UniversalWindowsPlatform\src\Microsoft.NETCore.UniversalWindowsPlatform.depproj] [D:\j\workspace\debug_windows---55156150\src\pkg\projects\Microsoft.NETCore.UniversalWindowsPlatform\src\Microsoft.NETCore.UniversalWindowsPlatform.depproj]
```

**Comment by chcosta** [comment]
@dotnet-bot test Windows_NT x86 Debug Build

**Comment by chcosta** [comment]
The error I saw in CI is concerning, but I don't think it's related to these changes, and it didn't repro.  I don't have a theory for what caused it.

@mmitche , have you seen this error in CI before?  perhaps there was some Jenkins crash that left a dirty machine?

```
removing the file 'C:\Users\dotnet-bot\AppData\Local\Temp\NuGetScratch\lock\31f4e521d883d8e9d7523dba4604fb7f02a3f352' will allow NuGet to continue. 
```

@gkhanna79 , how would you like me to proceed?

**Comment by gkhanna79** [comment]
Looks like your restart of the CI leg is green. If CI is green, please merge but keep an eye on the official builds and subsequent PRs incase this comes up.

**Comment by gkhanna79** [comment]
I presume the BT update is required for your change?

**Comment by chcosta** [comment]
Yes, the BuildTools update is required for this change so that we can align the assembly info we are embedding in PlatformAbstractions and DependencyModel with what we embed for other shipping assemblies.

**Pull request merged**
