### PR TITLE
Update dotnet-install script to 'dotnet/cli/master'.

### PR DESCRIPTION
**Pull request by eerhardt**
There have been bug fixes in the dotnet-install script in the CLI master branch that we should take advantage of.

For example:

https://github.com/dotnet/cli/pull/5850

@gkhanna79 @ramarag 

/cc @am11

### CODE REVIEW

**Comment by omajid** [comment]
Also many more:

- https://github.com/dotnet/cli/commit/d2bbe1faa294012cec60b640e6522e0674224d3f
- https://github.com/dotnet/cli/commit/3fde06faf84161cf8b6d09a0be0ad16e059ec52d
- https://github.com/dotnet/cli/commit/46a1d6f41ed12eba8703057b4b8f0c5e28628c99
- https://github.com/dotnet/cli/commit/4b233bdf82a3ac4f465bdc3caab2c90586adda2b

+1 for the core-setup's master branch to use dotnet-install.sh from cli's master branch.

**Comment by am11** [comment]
Thanks! 🌮 
Many `dotnet` repos are using bash function called `machine_has` to detect whether the utility is present. Would it make sense that we extract it out to build_tools repo say `commons.sh` and the repo scripts depend on it using `. path/where/build_tools/will_get_installed/scripts/commons.sh` semantics?

Some CoreFX built scripts are depending on  `which`.

**Comment by eerhardt** [comment]
> Would it make sense that we extract it out to build_tools repo say commons.sh

I'm not sure the effort/complexity is worth it for a 1 line function.

**Comment by eerhardt** [comment]
> Would it make sense that we extract it out to build_tools repo say commons.sh

Also, the dotnet-install scripts have to be completely independent.  They cannot rely on build_tools.  One reason is because installing 'dotnet' is required in order to restore build_tools.  😉

**Pull request merged**
