### PR TITLE
[release/2.1] Update to rc1 sdk

### PR DESCRIPTION
**Pull request by weshaggard**
I accidentally deleted my branch which closed out https://github.com/dotnet/core-setup/pull/4107 so I'm reopening a PR.

cc @Petermarcu @steveharter

### CODE REVIEW

**Comment by weshaggard** [comment]
@rohit21agrawal @rrelyea we are trying to update core-setup to use the latest SDK and we are hitting a failure in our tool initialization step because it appears something change in how incremental restore happens.
https://ci.dot.net/job/dotnet_core-setup/job/release_2.1/job/release_linux_x64_prtest/81/console
```
08:46:44 Running: /mnt/resource/j/workspace/dotnet_core-setup/release_2.1/release_linux_x64_prtest/Tools/dotnetcli/dotnet restore "/mnt/resource/j/workspace/dotnet_core-setup/release_2.1/release_linux_x64_prtest/packages/microsoft.dotnet.buildtools/2.1.0-rc1-02801-02/lib/tool-runtime/project.csproj" --source https://dotnet.myget.org/F/dotnet-core/api/v3/index.json --source https://dotnet.myget.org/F/dotnet-buildtools/api/v3/index.json --source https://api.nuget.org/v3/index.json 
08:46:44   Restoring packages for /mnt/resource/j/workspace/dotnet_core-setup/release_2.1/release_linux_x64_prtest/packages/microsoft.dotnet.buildtools/2.1.0-rc1-02801-02/lib/tool-runtime/project.csproj...
08:46:44   Installing Microsoft.CodeAnalysis.Common 2.6.0-beta3-62316-02.
08:46:44   Installing Microsoft.Cci 4.0.0-rc3-24214-00.
08:46:44   Installing Microsoft.NETCore.App 2.0.0.
08:46:44   Installing Microsoft.NETCore.DotNetAppHost 2.0.0.
08:46:44   Installing Microsoft.CodeAnalysis.VisualBasic 2.6.0-beta3-62316-02.
08:46:44   Installing Microsoft.CodeAnalysis.CSharp 2.6.0-beta3-62316-02.
08:46:44   Installing Microsoft.Net.Compilers.netcore 2.6.0-beta3-62316-02.
08:46:44   Installing NETStandard.Library 2.0.0.
08:46:44   Installing Microsoft.NETCore.Platforms 2.0.0.
08:46:44   Installing Microsoft.NETCore.DotNetHostPolicy 2.0.0.
08:46:44   Installing Microsoft.CodeAnalysis.Compilers 2.6.0-beta3-62316-02.
08:46:44   Installing Microsoft.NETCore.DotNetHostResolver 2.0.0.
08:46:44   Generating MSBuild file /mnt/resource/j/workspace/dotnet_core-setup/release_2.1/release_linux_x64_prtest/packages/microsoft.dotnet.buildtools/2.1.0-rc1-02801-02/lib/tool-runtime/obj/project.csproj.nuget.g.props.
08:46:44   Generating MSBuild file /mnt/resource/j/workspace/dotnet_core-setup/release_2.1/release_linux_x64_prtest/packages/microsoft.dotnet.buildtools/2.1.0-rc1-02801-02/lib/tool-runtime/obj/project.csproj.nuget.g.targets.
08:46:44   Restore completed in 7.37 sec for /mnt/resource/j/workspace/dotnet_core-setup/release_2.1/release_linux_x64_prtest/packages/microsoft.dotnet.buildtools/2.1.0-rc1-02801-02/lib/tool-runtime/project.csproj.
08:46:44 Running: /mnt/resource/j/workspace/dotnet_core-setup/release_2.1/release_linux_x64_prtest/Tools/dotnetcli/dotnet publish "/mnt/resource/j/workspace/dotnet_core-setup/release_2.1/release_linux_x64_prtest/packages/microsoft.dotnet.buildtools/2.1.0-rc1-02801-02/lib/tool-runtime/project.csproj" -f netcoreapp2.0 -o /mnt/resource/j/workspace/dotnet_core-setup/release_2.1/release_linux_x64_prtest/Tools
08:46:44 Microsoft (R) Build Engine version 15.7.177.53362 for .NET Core
08:46:44 Copyright (C) Microsoft Corporation. All rights reserved.
08:46:44 
08:46:44   Restoring packages for /mnt/resource/j/workspace/dotnet_core-setup/release_2.1/release_linux_x64_prtest/packages/microsoft.dotnet.buildtools/2.1.0-rc1-02801-02/lib/tool-runtime/project.csproj...
08:46:44   Restoring packages for /mnt/resource/j/workspace/dotnet_core-setup/release_2.1/release_linux_x64_prtest/packages/microsoft.dotnet.buildtools/2.1.0-rc1-02801-02/lib/tool-runtime/project.csproj...
08:46:44 
```

We call restore which succeeds and then we call publish (not passing in the restore sources) which fails because it tries to do a restore when it doesn't need to and since it doesn't have the sources it fails. I've had a very hard time repro'ing this locally but I do have a connection to a CI machine the repro's it 100% if you guys want to take a look. 

If I update our tools to pass `--no-restore` to the publish step everything works as expected but it would be good if you guys could investigate the incremental restore issue.

**Comment by rohit21agrawal** [comment]
@weshaggard is this the RC build? or post RC? We did change the version of NuGet between RC and post RC, so knowing which version is being built would help us determine if the payload change is the culprit.

CC: @nikolev for why restore is not no-oping.

**Comment by nkolev92** [comment]
The restore sources affect no-op. 
Changing the sources means that there's no no-op. 
I'm not aware of any changes that could affect this. 

Normally even though no-op is defeated, if all the same packages were downloaded in a previous restore, the follow-up restore would be completely offline, unless there's a version miss. 
Meaning a package that has a dependency on some other package with a lower bound that can't be discovered.

**Comment by weshaggard** [comment]
>@weshaggard is this the RC build? 

This is the current 2.1 RC candidate build.

**Comment by weshaggard** [comment]
Once https://github.com/dotnet/core-setup/pull/4121 is merged that should update the toolset to workaround the issue here and we can retry CI.

**Comment by weshaggard** [comment]
@dotnet-bot test this please

**Comment by weshaggard** [comment]
So we have a high degree of confidence that this is caused by https://github.com/dotnet/corefx/issues/29095 and is now fixed in master https://github.com/dotnet/corefx/pull/29502 with plans to port to release/2.1.

**Comment by weshaggard** [comment]
Given that it is a corefx issue and we use centos for our official builds (https://github.com/dotnet/core-setup/blob/release/2.1/buildpipeline/pipeline.json#L21) I'm going to merge this PR and we can expect that the linux x64 leg will continue to fail until we get a newer SDK which contains the corefx fix. 

For reference folks that hit the issue will see errors similar to:
```
10:21:38 /tmp/.NETCoreApp,Version=v2.0.AssemblyAttributes.cs(4,20): error CS0400: The type or namespace name 'System' could not be found in the global namespace (are you missing an assembly reference?) [/mnt/resource/j/workspace/dotnet_core-setup/release_2.1/release_linux_x64_prtest/packages/microsoft.dotnet.buildtools/2.1.0-rc1-02803-01/lib/tool-runtime/project.csproj]
10:21:38 obj/Debug/netcoreapp2.0/project.AssemblyInfo.cs(10,12): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?) [/mnt/resource/j/workspace/dotnet_core-setup/release_2.1/release_linux_x64_prtest/packages/microsoft.dotnet.buildtools/2.1.0-rc1-02803-01/lib/tool-runtime/project.csproj]
10:21:38 obj/Debug/netcoreapp2.0/project.AssemblyInfo.cs(11,12): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?) [/mnt/resource/j/workspace/dotnet_core-setup/release_2.1/release_linux_x64_prtest/packages/microsoft.dotnet.buildtools/2.1.0-rc1-02803-01/lib/tool-runtime/project.csproj]
10:21:38 obj/Debug/netcoreapp2.0/project.AssemblyInfo.cs(12,12): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?) [/mnt/resource/j/workspace/dotnet_core-setup/release_2.1/release_linux_x64_prtest/packages/microsoft.dotnet.buildtools/2.1.0-rc1-02803-01/lib/tool-runtime/project.csproj]
10:21:38 obj/Debug/netcoreapp2.0/project.AssemblyInfo.cs(13,12): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?) [/mnt/resource/j/workspace/dotnet_core-setup/release_2.1/release_linux_x64_prtest/packages/microsoft.dotnet.buildtools/2.1.0-rc1-02803-01/lib/tool-runtime/project.csproj]
10:21:38 obj/Debug/netcoreapp2.0/project.AssemblyInfo.cs(14,12): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?) [/mnt/resource/j/workspace/dotnet_core-setup/release_2.1/release_linux_x64_prtest/packages/microsoft.dotnet.buildtools/2.1.0-rc1-02803-01/lib/tool-runtime/project.csproj]
10:21:38 obj/Debug/netcoreapp2.0/project.AssemblyInfo.cs(15,12): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?) [/mnt/resource/j/workspace/dotnet_core-setup/release_2.1/release_linux_x64_prtest/packages/microsoft.dotnet.buildtools/2.1.0-rc1-02803-01/lib/tool-runtime/project.csproj]
10:21:38 obj/Debug/netcoreapp2.0/project.AssemblyInfo.cs(16,12): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?) [/mnt/resource/j/workspace/dotnet_core-setup/release_2.1/release_linux_x64_prtest/packages/microsoft.dotnet.buildtools/2.1.0-rc1-02803-01/lib/tool-runtime/project.csproj]
10:21:38 /tmp/.NETCoreApp,Version=v2.0.AssemblyAttributes.cs(4,71): error CS0518: Predefined type 'System.String' is not defined or imported [/mnt/resource/j/workspace/dotnet_core-setup/release_2.1/release_linux_x64_prtest/packages/microsoft.dotnet.buildtools/2.1.0-rc1-02803-01/lib/tool-runtime/project.csproj]
10:21:38 /tmp/.NETCoreApp,Version=v2.0.AssemblyAttributes.cs(4,99): error CS0246: The type or namespace name 'FrameworkDisplayName' could not be found (are you missing a using directive or an assembly reference?) [/mnt/resource/j/workspace/dotnet_core-setup/release_2.1/release_linux_x64_prtest/packages/microsoft.dotnet.buildtools/2.1.0-rc1-02803-01/lib/tool-runtime/project.csproj]
10:21:38 /tmp/.NETCoreApp,Version=v2.0.AssemblyAttributes.cs(4,122): error CS0518: Predefined type 'System.String' is not defined or imported [/mnt/resource/j/workspace/dotnet_core-setup/release_2.1/release_linux_x64_prtest/packages/microsoft.dotnet.buildtools/2.1.0-rc1-02803-01/lib/tool-runtime/project.csproj]
10:21:38 obj/Debug/netcoreapp2.0/project.AssemblyInfo.cs(10,55): error CS0518: Predefined type 'System.String' is not defined or imported [/mnt/resource/j/workspace/dotnet_core-setup/release_2.1/release_linux_x64_prtest/packages/microsoft.dotnet.buildtools/2.1.0-rc1-02803-01/lib/tool-runtime/project.csproj]
10:21:38 obj/Debug/netcoreapp2.0/project.AssemblyInfo.cs(11,61): error CS0518: Predefined type 'System.String' is not defined or imported [/mnt/resource/j/workspace/dotnet_core-setup/release_2.1/release_linux_x64_prtest/packages/microsoft.dotnet.buildtools/2.1.0-rc1-02803-01/lib/tool-runtime/project.csproj]
10:21:38 obj/Debug/netcoreapp2.0/project.AssemblyInfo.cs(12,59): error CS0518: Predefined type 'System.String' is not defined or imported [/mnt/resource/j/workspace/dotnet_core-setup/release_2.1/release_linux_x64_prtest/packages/microsoft.dotnet.buildtools/2.1.0-rc1-02803-01/lib/tool-runtime/project.csproj]
10:21:38 obj/Debug/netcoreapp2.0/project.AssemblyInfo.cs(13,68): error CS0518: Predefined type 'System.String' is not defined or imported [/mnt/resource/j/workspace/dotnet_core-setup/release_2.1/release_linux_x64_prtest/packages/microsoft.dotnet.buildtools/2.1.0-rc1-02803-01/lib/tool-runtime/project.csproj]
10:21:38 obj/Debug/netcoreapp2.0/project.AssemblyInfo.cs(14,55): error CS0518: Predefined type 'System.String' is not defined or imported [/mnt/resource/j/workspace/dotnet_core-setup/release_2.1/release_linux_x64_prtest/packages/microsoft.dotnet.buildtools/2.1.0-rc1-02803-01/lib/tool-runtime/project.csproj]
10:21:38 obj/Debug/netcoreapp2.0/project.AssemblyInfo.cs(15,53): error CS0518: Predefined type 'System.String' is not defined or imported [/mnt/resource/j/workspace/dotnet_core-setup/release_2.1/release_linux_x64_prtest/packages/microsoft.dotnet.buildtools/2.1.0-rc1-02803-01/lib/tool-runtime/project.csproj]
10:21:38 obj/Debug/netcoreapp2.0/project.AssemblyInfo.cs(16,55): error CS0518: Predefined type 'System.String' is not defined or imported [/mnt/resource/j/workspace/dotnet_core-setup/release_2.1/release_linux_x64_prtest/packages/microsoft.dotnet.buildtools/2.1.0-rc1-02803-01/lib/tool-runtime/project.csproj]
10:21:38 Program.cs(6,7): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?) [/mnt/resource/j/workspace/dotnet_core-setup/release_2.1/release_linux_x64_prtest/packages/microsoft.dotnet.buildtools/2.1.0-rc1-02803-01/lib/tool-runtime/project.csproj]
10:21:38 /tmp/.NETCoreApp,Version=v2.0.AssemblyAttributes.cs(2,7): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?) [/mnt/resource/j/workspace/dotnet_core-setup/release_2.1/release_linux_x64_prtest/packages/microsoft.dotnet.buildtools/2.1.0-rc1-02803-01/lib/tool-runtime/project.csproj]
10:21:38 /tmp/.NETCoreApp,Version=v2.0.AssemblyAttributes.cs(3,7): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?) [/mnt/resource/j/workspace/dotnet_core-setup/release_2.1/release_linux_x64_prtest/packages/microsoft.dotnet.buildtools/2.1.0-rc1-02803-01/lib/tool-runtime/project.csproj]
10:21:38 obj/Debug/netcoreapp2.0/project.AssemblyInfo.cs(7,7): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?) [/mnt/resource/j/workspace/dotnet_core-setup/release_2.1/release_linux_x64_prtest/packages/microsoft.dotnet.buildtools/2.1.0-rc1-02803-01/lib/tool-runtime/project.csproj]
10:21:38 obj/Debug/netcoreapp2.0/project.AssemblyInfo.cs(8,7): error CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?) [/mnt/resource/j/workspace/dotnet_core-setup/release_2.1/release_linux_x64_prtest/packages/microsoft.dotnet.buildtools/2.1.0-rc1-02803-01/lib/tool-runtime/project.csproj]
10:21:38 Program.cs(10,18): error CS0518: Predefined type 'System.Object' is not defined or imported [/mnt/resource/j/workspace/dotnet_core-setup/release_2.1/release_linux_x64_prtest/packages/microsoft.dotnet.buildtools/2.1.0-rc1-02803-01/lib/tool-runtime/project.csproj]
10:21:38 Program.cs(12,32): error CS0518: Predefined type 'System.String' is not defined or imported [/mnt/resource/j/workspace/dotnet_core-setup/release_2.1/release_linux_x64_prtest/packages/microsoft.dotnet.buildtools/2.1.0-rc1-02803-01/lib/tool-runtime/project.csproj]
10:21:38 Program.cs(12,23): error CS0518: Predefined type 'System.Int32' is not defined or imported [/mnt/resource/j/workspace/dotnet_core-setup/release_2.1/release_linux_x64_prtest/packages/microsoft.dotnet.buildtools/2.1.0-rc1-02803-01/lib/tool-runtime/project.csproj]
10:21:38 
```

In my local testing of this I also saw issues were when targeting Microsoft.NETCore.App 2.0.0 (netcoreapp2.0) the sdk/nuget doesn't correctly include Microsoft.NETCore.App in the assets file which is what leads to the above compile errors.

**Pull request merged**
