### PR TITLE
Fix stage chaining, stage names were renamed

### PR DESCRIPTION
**Pull request by JohnTortugo**
[Stage names were renamed in Arcade templates](https://github.com/dotnet/arcade/pull/3888). 

This PR adjust for the new names.

/cc @dagood @mmitche @riarenas

### CODE REVIEW

**Comment by JohnTortugo** [comment]
I don't have privileges to re-run the build or to merge the PR.

**Comment by dagood** [comment]
I kicked off a retry.

**Comment by JohnTortugo** [comment]
Things look good. Feel free to merge. Thanks.

**Pull request merged**
