### PR TITLE
Use SemVer v2 versioning

### PR DESCRIPTION
**Pull request by dagood**
This is an attempt to create SemVer v2 artifacts using BuildTools. We want this for 5.0.0-... builds to avoid getting locked into SemVer v1. (Discussion at https://github.com/dotnet/core-setup/issues/6825.)

### CODE REVIEW

**Comment by dagood** [comment]
Confirmed that with this change, my local build of nupkgs and the Windows bundle installer are now using the semver v2 version.

@jeffschwMSFT, @sdmaclea, @wtgodbe, any concern about adding this to https://github.com/dotnet/core-setup/pull/7221 to make sure semver v2 is enabled in the very first build of 5.0.0-preview0?

This could break the official build or downstream builds in an unexpected way, but that may be better than getting locked into semver v2.

/cc @dleeapho

**Comment by wtgodbe** [comment]
I'm OK with that, we have plenty of runway for 5.0 if something in the official build breaks 😄

**Comment by sdmaclea** [comment]
I don't have any concerns.

**Comment by dagood** [comment]
I added a fix for the Linux glibc leg failure, squashed, and pushed these changes to https://github.com/dotnet/core-setup/pull/7221. Closing this one.

**Pull request closed without merging**
