### PR TITLE
[release/2.1] Move to Azure DevOps for PRs

### PR DESCRIPTION
**Pull request by mmitche**
- Please add a description for changes you are making.
- If there is an issue related to this PR, please add a reference to it.
- If this PR should not run tests please add say skip_ci_please in this description replacing the underscores with spaces.

### CODE REVIEW

**Comment by mmitche** [comment]
@wtgodbe We don't expect the tizen build to pass, right?

**Comment by wtgodbe** [comment]
@mmitche that's right

**Comment by mmitche** [comment]
> @mmitche that's right

Should we just remove it from the new AzDO side?

**Comment by mmitche** [comment]
This also should apply to 2.2 (same netci.groovy file)

**Comment by wtgodbe** [comment]
Yeah as far as I know Tizen was abandoned in 2.x, we can probably get away with removing it from CI.

**Comment by mmitche** [comment]
Ported the musl config.

**Comment by mmitche** [comment]
It works!

**Pull request merged**
