### PR TITLE
Add openSUSE 42.1 and Ubuntu 16.10 runs to Jenkins CI

### PR DESCRIPTION
**Pull request by mellinoe**
These builds already work, we just don't run them in CI.

### CODE REVIEW

**Comment by mellinoe** [comment]
@dotnet-bot Test CI please

**Comment by mellinoe** [comment]
https://ci.dot.net/job/dotnet_core-setup/job/master/job/GenPRTest/job/debug_opensuse42.1_x64_prtest/1/
https://ci.dot.net/job/dotnet_core-setup/job/master/job/GenPRTest/job/release_ubuntu16.10_x64_prtest/1/

**Comment by gkhanna79** [comment]
LGTM. Are these CI changes in release/1.1.0 as well?

**Comment by mellinoe** [comment]
Yeah, same exact changes should be able to go into release/1.1.0; I'll follow up.

**Pull request merged**
