### PR TITLE
Changing formatting for lists of items in cells

### PR DESCRIPTION
**Pull request by Petermarcu**

### CODE REVIEW

**Comment by gkhanna79** [comment]
The links are not archives but pointers to actual Debian installers that need to be installed.

**Comment by Petermarcu** [comment]
Interesting, the shared framework one is. Should that one be a deb too then? I saw that was a tar.gz and assumed the others were.

**Comment by gkhanna79** [comment]
The SharedFW should be a deb as well and looks like a typo on my part. Please do correct it since you are at it :)

Also, do you also want to update the list for archives for platforms for which installers are produced?

**Comment by Petermarcu** [comment]
Yes, I think we should have links to both installers and archives. I'm going to get this one through to start because I don't have all the other links figured out. I'll fix the Archives wording switch tar.gz to deb in this PR.

**Comment by Petermarcu** [comment]
Done. This doesn't resolve the issue I reopened but does fix some formatting that will help that issue and points to debs instead of tar.gz's for the Ubuntu Shared Framework.

**Comment by Petermarcu** [comment]
@gkhanna79 , you good with this change?

**Comment by gkhanna79** [comment]
LGTM.

**Pull request merged**
