### PR TITLE
Fixes for Ubuntu Arm32 builds

### PR DESCRIPTION
**Pull request by gkhanna79**
Fix tag names used for Ubuntu 14.04 and explicitly pass the value of PUBLISH_TO_AZURE_BLOB variable when invoking the build in Docker container.

### CODE REVIEW

**Comment by gkhanna79** [comment]
@dotnet-bot test this please

**Comment by gkhanna79** [comment]
@mmitche Is CI not working?

**Comment by jyoungyun** [comment]
@gkhanna79 Now CI server is not working. :(

**Comment by gkhanna79** [comment]
Yes, I am validating the basic build locally and if it is clean, I will merge this.

**Comment by gkhanna79** [comment]
Validated locally. Merging since CI is not working and need this to attempt unblock of Ubuntu Arm32.

**Pull request merged**
