### PR TITLE
Revert various changes from 1.0.2

### PR DESCRIPTION
**Pull request by gkhanna79**
This PR reverts various changes we took in 1.0.2 but should be in 1.0.3:

1) Networking fixes
2) RID fallback graph update for Sierra

Post this change, we only have the fixes for the OSX PATH issue on Sierra.

@weshaggard @ericstj PTAL

CC @leecow @schellap @Petermarcu @dagood @wtgodbe

### CODE REVIEW

**Comment by gkhanna79** [comment]
@weshaggard PTAL as I would like to get this change in at the earliest.

**Comment by gkhanna79** [comment]
Also, the corresponding change with the stabilization of versions is at https://github.com/dotnet/core-setup/pull/448

**Comment by weshaggard** [comment]
I had a quick look at I see you didn't rollback the following commits:
https://github.com/dotnet/core-setup/commit/cb0635ee4df5ae4bb94792f5c7c426224da52b5f
https://github.com/dotnet/core-setup/commit/7d1231b47177cd2867cbe64df10d4627cb8158b1
https://github.com/dotnet/core-setup/commit/ac42c501dc6c31a65c18690174f18b77c12bf2ce
https://github.com/dotnet/core-setup/commit/9741355b67a62659ef74bb417588c799251f4061

Those might be intentional but I wanted to at least point them out to you.

Otherwise the list looks correct.

**Comment by gkhanna79** [comment]
Thansk @weshaggard. Yes, I intentionally didnt' revert them since they are engineering fixes that were required to get the builds done correctly in the pipeline. 

I will merge this change to get the build out.

**Comment by gkhanna79** [comment]
Merging the changes. 

@wtgodbe Please keep an eye on the build that comes out of this.

**Comment by gkhanna79** [comment]
@dagood @wtgodbe Ins't https://devdiv.visualstudio.com/DevDiv/_build/index?definitionId=4187&_a=completed expected to commence a build once the PR is committed? Or, do I need to queue a build explicitly?

**Comment by gkhanna79** [comment]
Kicked off https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=372868&_a=summary

**Comment by dagood** [comment]
It's manual, there is no subscription to trigger 1.0.0 builds on merge: https://github.com/dotnet/versions/blob/5ffc2e4cb72cbd0f10eade816f5883c22b85d273/Maestro/subscriptions.json#L482-L499. (I believe we wanted to keep it that way to make 1.0.0 builds very intentional.)

**Comment by gkhanna79** [comment]
@dagood https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=372868&_a=summary failed. The failures look like signing infra issues - does that sound right to you?

**Comment by dagood** [comment]
Agreed. Last time I saw `Internal file signing error has occurred` I filed an issue, but it didn't get answered for a while and it didn't repro, so I think the best thing to do for now is rerun the build (after a dummy commit).

**Pull request merged**
