### PR TITLE
[ARM/CI]Enable ARM CI script for cross build

### PR DESCRIPTION
**Pull request by jyoungyun**
Related issue: #1512

### CODE REVIEW

**Comment by gkhanna79** [comment]
@jyoungyun Looks like the build succeeded but was marked as failed in CI above. Here is the output from the log (https://ci.dot.net/job/dotnet_core-setup/job/master/job/release_ubuntu_arm_prtest/2/consoleFull):

```
18:14:44 Build succeeded
18:14:44 ++ id -u -n
18:14:44 + sudo chown -R dotnet-bot ./bin
18:14:44 chown: cannot access ‘./bin’: No such file or directory
18:14:44 + handle_exit
18:14:44 + set +x
18:14:44 The script is exited. Cleaning environment..
18:14:44 Build step 'Execute shell' marked build as failure
18:14:44 [xUnit] [INFO] - Starting to record.
18:14:44 [xUnit] [INFO] - Processing xUnit.Net-v2 (default)
18:15:08 [xUnit] [INFO] - [xUnit.Net-v2 (default)] - 1 test report file(s) were found with the pattern '**/*-testResults.xml' relative to '/mnt/j/workspace/dotnet_core-setup/master/release_ubuntu_arm_prtest' for the testing framework 'xUnit.Net-v2 (default)'.
18:15:11 [xUnit] [INFO] - Check 'Failed Tests' threshold.
18:15:11 [xUnit] [INFO] - Check 'Skipped Tests' threshold.
18:15:11 [xUnit] [INFO] - Setting the build status to FAILURE
18:15:11 [xUnit] [INFO] - Stopping recording.
18:15:11 [Current build status] check if current [FAILURE] is worse or equals then [SUCCESS] and better or equals then [SUCCESS]
18:15:11 Run condition [Current build status] preventing perform for step [[Archive the artifacts]]
18:15:11 [BFA] Scanning build for known causes...
18:15:15 [BFA] No failure causes found
18:15:15 [BFA] Done. 3s
18:15:22 Notifying endpoint with id 'HTTP:helix-int-notification-url'
18:15:22 Notifying endpoint with id 'HTTP:helix-prod-notification-url'
18:15:22 Notifying endpoint with id 'HTTP:legacy-notification-url'
18:15:22 Setting status of 15ade21696090f0659edcddd70308a82b3a2bf8e to FAILURE with url https://ci.dot.net/job/dotnet_core-setup/job/master/job/release_ubuntu_arm_prtest/2/ and message: 'Build finished. '
18:15:22 Using context: Ubuntu arm Release Build
18:15:22 [WS-CLEANUP] Deleting project workspace...[WS-CLEANUP] done
18:15:22 Finished: FAILURE
```

Can you PTAL?

**Comment by gkhanna79** [comment]
Also, can you please add Ubuntu 16.04 Arm32 CI support as well at https://github.com/dotnet/core-setup/blob/master/netci.groovy#L13?

**Comment by hqueue** [comment]
I think following line 215 of scripts/arm32_ci_script.sh  should be updated, it's valid at coreclr and corefx but not in core-setup.
```
 sudo chown -R $(id -u -n) ./bin
```

Related log:
```
18:14:44 chown: cannot access ‘./bin’: No such file or directory
```

**Comment by jyoungyun** [comment]
@gkhanna79 I fixed the arm32 CI script. And it works well! :) And acutally I wanna add Ubuntu 16.04 Arm32 CI but I'm not sure what images will work well for our CI job. Anyway I will try it. I think maybe 'latest-or-auto-docker' in 'Ubuntu16.04' will support our CI job without any problems. I will make another PR for supporting Ubuntu 16.04 arm CI job. This PR is ready to merge. PTAL~

**Comment by gkhanna79** [comment]
I have merged this @jyoungyun. Please kick off a dummy PR to confirm everything looks good.

**Pull request merged**
