### PR TITLE
Add support for clang 4.0 cross build

### PR DESCRIPTION
**Pull request by gbalykov**
cc @alpencolt @Dmitri-Botcharnikov

### CODE REVIEW

**Comment by kasper3** [comment]
Note that CoreCLR and CoreFX builds with clang v3.x, v4, v5 and v6. It would be much profitable if we extract out these "detect clang + llvm + lldb" mechanics into one script and place it in a common location (dotnet/buildtools) to avoid duplicating the effort and be in this desync situation all the time.

**Comment by gbalykov** [comment]
@Petermarcu, could this pull request be merged?

**Comment by gbalykov** [comment]
cc @weshaggard

**Comment by weshaggard** [comment]
@gbalykov do you think this will address the CI failure we are seeing in https://github.com/dotnet/core-setup/pull/4157?

**Comment by gbalykov** [comment]
@weshaggard, yes, looks like it fixed them

**Pull request merged**
