### PR TITLE
Update NETStandard.Library version

### PR DESCRIPTION
**Pull request by zamont**
We need to update this version for internal testing purposes. The maestro update is failing but if this update does not cause any test regressions, we'd like to move forward with this update.

### CODE REVIEW

**Comment by zamont** [comment]
@joperezr @ericstj @weshaggard We need to get the NetStandard.Library reference in the UWP metapackage updated soon. Is there any issue updating this individual dependency while not updating others?

**Comment by joperezr** [comment]
No issue, its fine to just update that one manually when others are holding back the update. If you want to do it right though, you should also change the standard repo hash in the property group above this.

**Comment by joperezr** [comment]
I took the liberty to push to your PR. In case you need to do this in the future, the right way is to first only update the current Ref of the dependency you want to update by picking the commit in the dotnet/versions repo that contains the version of the dependency that you want. In this case, since we wanted latest I just went to https://github.com/dotnet/versions/tree/master/build-info/dotnet/standard/master and got the latest commit there which was `5f7c216b2b316b1f0105d3d6957f74e32b9213bf`. Once you have that changed in dependencies.props, just call from the root: `msbuild build.proj /t:UpdateDependencies` and that will automatically update all of the references required based on the ref change that you made.

**Comment by zamont** [comment]
Ah, that makes sense. Thanks for the information and the correct commit Jose. I will merge this once the CI checks are all green.

**Comment by joperezr** [comment]
Looks like we can merge now, the OSX build succeeded but for some reason it just got stuck int Archiving artifacts stage (been stuck for 30 mins now). cc @dotnet/dnceng

**Comment by mmitche** [comment]
@joperezr It could be two things:  1) slow network perf, 2) Huge archive.

@dotnet/dnceng PTAL, just to make sure we're not going to see huge archives.

**Comment by ellismg** [comment]
The resulting archive was 360MB.  Note that I don't think we actually need to be archiving these artifacts anymore (I added archiving in the past because it made it easy to get packages before we had official build support for some stuff).  Maybe we should just turn archiving off?

**Pull request merged**
