### PR TITLE
Build PlatformAbstractions and DependencyModel 1.1.1-servicing

### PR DESCRIPTION
**Pull request by schellap**
Fixes https://github.com/dotnet/core-setup/issues/715

Cc @gkhanna79

### CODE REVIEW

**Comment by gkhanna79** [comment]
@dotnet-bot test this please

**Comment by gkhanna79** [comment]
LGTM

**Comment by gkhanna79** [comment]
@mmitche Is CI down?

**Comment by mmitche** [comment]
@dotnet-bot test this please

**Comment by gkhanna79** [comment]
@dotnet-bot test this please

**Comment by mmitche** [comment]
@dotnet-bot test this please

**Comment by gkhanna79** [comment]
@mmitche OSX still failed due to the same issue. Can you PTAL?

**Comment by mmitche** [comment]
FYI the OSX build won't relaunch because the machines are currently being moved

**Comment by gkhanna79** [comment]
Looks like we have good build. @schellap Do you want to merge it and queue an official build?

CC @dagood

**Comment by schellap** [comment]
@dotnet-bot test OSX x64 Release Build

**Comment by schellap** [comment]
@dotnet-bot test OSX x64 Release Build please

**Comment by dagood** [comment]
I've reuploaded the original 1.1.0 packages to MyGet.

**Comment by gkhanna79** [comment]
Queued https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=458815&_a=summary to pickup the change.

**Comment by schellap** [comment]
@gkhanna79 thanks for firing the build.

**Pull request merged**
