### PR TITLE
Remove NugetRestoreCommand, since it is not used in core-setup.

### PR DESCRIPTION
**Pull request by eerhardt**
@chcosta @weshaggard

### CODE REVIEW

**Comment by weshaggard** [comment]
cc @ericstj as I believe he uses it for depproj's. However this is something that I recently moved into BuildTools with the 2.0 changes.

**Comment by ericstj** [comment]
No I don't use that one.

**Comment by eerhardt** [comment]
> However this is something that I recently moved into BuildTools with the 2.0 changes.

Are you saying BuildTools now depends on `mono` as well?  I think we need to not depend on 'mono' in any of our repos.

**Comment by weshaggard** [comment]
No BuildTools doesn't depend on mono. I mistoke this for the DnuRestoreCommands, which I moved into BuildTools https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.Build.Tasks/PackageFiles/Build.Common.props#L59. Once we update this repo to use BuildTools 2.0 then those can also be deleted.

**Comment by eerhardt** [comment]
Looks like it does:

https://github.com/dotnet/buildtools/blob/c3eb52fd221fe1dab172f5324f29712dbbacf8dc/dir.props#L81

```
    <NugetRestoreCommand Condition="'$(OsEnvironment)'=='Unix'">mono $(NuGetRestoreCommand)</NugetRestoreCommand>
```

**Comment by weshaggard** [comment]
That is for the building of BuildTools as opposed to the consumption of BuildTools. I don't think we actually use that restore command for building of BuildTools any longer either so we can probably delete it there as well.

**Pull request merged**
