### PR TITLE
Use the DotNetCore-Test pool which has WS2016 agents

### PR DESCRIPTION
**Pull request by jcagme**
Use the DotNetCore-Test pool for sign task since it contains WS2016 agents

### CODE REVIEW

**Comment by weshaggard** [comment]
@jcagme can you please put together a change that will fail the build if we don't have anything to sign? I would like to get that in before we spin our official builds so that we can ensure we don't hit this issue again.

**Comment by jcagme** [comment]
@weshaggard I opened issue https://github.com/dotnet/core-eng/issues/1774 to track this. Either @Chrisboh or @markwilkie can make the call if they want me doing this now or they want someone else on this

**Comment by Chrisboh** [comment]
@MattGal Do you think you could take a look at this as FR?

**Comment by jcagme** [comment]
I fixed the referenced issue already. No more action is required here. Feel free to ping me if needed

**Comment by MattGal** [comment]
@Chrisboh I did a retroactive CR and it looks like we just need error checking in a couple more places otherwise we should be good to go.  @jcagme is prepping this now.

**Pull request merged**
