### PR TITLE
Updated dotnet.hithub.io URLs to microsoft.com/net

### PR DESCRIPTION
**Pull request by svick**
Fixes https://github.com/dotnet/core/issues/235.

### CODE REVIEW

**Comment by akoeplinger** [comment]
should we use https://dot.net/core instead? It redirects to the same page, but looks better :)

**Comment by svick** [comment]
@akoeplinger Done.

**Comment by karelz** [comment]
This slipped through and was ignored for quite some time :(.
@svick can you please rebase, so that we can merge it?

**Comment by svick** [comment]
@karelz Done.

**Comment by karelz** [comment]
Thanks for your contribution @svick!

**Pull request merged**
