### PR TITLE
move branch_name to release/1.0.0

### PR DESCRIPTION
**Pull request by brthor**
@eerhardt 

Last one went against the wrong branch.

### CODE REVIEW

**Comment by brthor** [comment]
@dotnet-bot test   Ubuntu x64 Release Build please

**Comment by eerhardt** [comment]
:shipit:

**Comment by schellap** [comment]
Are we making fixes only in the release branch from now on?

**Comment by eerhardt** [comment]
> Are we making fixes only in the release branch from now on?

You should be making fixes you want included in 1.0.0 RTM in the release/1.0.0 branch.

**Comment by joshfree** [comment]
@schellap it's the standard 1.0.0 = /release/1.0.0 and 1.1.0 = master split.  In general you should make a fix to master, prove that it's stable, then port to /release/1.0.0

**Comment by schellap** [comment]
> You should be making fixes you want included in 1.0.0 RTM in the release/1.0.0 branch.
My question was because in CLI repo, we had a merge process between release/1.0.0 and master.

**Comment by schellap** [comment]
@joshfree, thanks! sounds like a dev rel split.

**Pull request merged**
