### PR TITLE
The SDK version rolls up only upon 'minor-patch' versions

### PR DESCRIPTION
**Pull request by ghost**
The SDK version rolls up only upon 'minor-patch' versions where the 'minor-patch' version is defined as the last two digits of the 'patch' version.

**fx_muxer.cpp**
To be a candidate for roll-up, the compared version must match the global.json's version in the major, minor, and the 'major-patch' versions.

**TwoPart-global.json 
SingleDigit-global.json** 
For SDK roll-up tests, we'll need two types of global.json

**GivenThatICareAboutMultilevelSDKLookup.cs** 
Add several tests around the two-part patch versioning & patch roll-ups.

**Testing:**
Full build and test on Windows x64

@dotnet/dotnet-cli 
@KathleenDollard

### CODE REVIEW

**Review by mmitche — APPROVED** [review]

**Comment by johnbeisner** [comment]
@steveharter 
The Tizen CI leg failed on this PR. It seems to me that the failure does not have anything to do with my code change. Can you resolve the nuget issue so we can move forward.

**Review by eerhardt — APPROVED** [review]
Looks reasonable to me.

**Review by nguerrera — APPROVED** [review]

**Comment by steveharter** [comment]
@johnbeisner about the Tizen CI leg. Can you rebase against master and try again? It is looking for preview1 bits but can only find preview2.

**Review by steveharter — APPROVED** [review]

**Comment by eerhardt** [comment]
I just noticed that this PR is against `release/2.1`.  Do we have approval for this change at this time?  I didn't see an email to .net core shiproom.

/cc @Petermarcu

**Comment by eerhardt** [comment]
As for the Tizen leg being broken in this branch, that is a known problem.  See https://github.com/dotnet/core-setup/issues/3706

**Comment by johnbeisner** [comment]
@MattGertz 
@livarcocc 
Am I targeting the correct branch in core-setup?

**Comment by eerhardt** [comment]
The process for `dotnet/core*` repos is to submit the first PR to `master`.  When that is merged and stabilized, send an email to `.NET Core Shiproom` requesting approval to port the change into a `release/*` branch.

**Comment by johnbeisner** [comment]
@eerhardt 
Thanks Eric - modifying the PR now.

**Comment by nguerrera** [comment]
Looks like this was never ported to release/2.1. I almost ported it with another change due to an unexpected merge conflict. Should we be taking this for servicing? @johnbeisner @livarcocc

**Comment by nguerrera** [comment]
I was wrong here, this change did make it into 2.1.

**Pull request merged**
