### PR TITLE
Merging Readme table

### PR DESCRIPTION
**Pull request by Petermarcu**
skipciplease

### CODE REVIEW

**Comment by Petermarcu** [comment]
@mmitche , Did skipciplease need to be formatted differently to make CI skip? Should there have been spaces in it?

**Comment by Petermarcu** [comment]
@gkhanna79 , can you take a look?

**Comment by Petermarcu** [comment]
Fix for https://github.com/dotnet/core-setup/issues/579

**Comment by mmitche** [comment]
I think it's skip ci please (with spaces)

**Comment by Petermarcu** [comment]
Ok, the template instructions didn't make that obvious. I'll see if I can figure out how to edit it.

**Comment by gkhanna79** [comment]
Lgtm

**Pull request merged**
