### PR TITLE
Add version information to hostfxr component

### PR DESCRIPTION
**Pull request by schellap**
@gkhanna79 PR #449 porting to 1.1.0

Cc @leecow

### CODE REVIEW

**Comment by schellap** [comment]
Fixes https://github.com/dotnet/core-setup/issues/444

**Comment by gkhanna79** [comment]
Please hold off on merging this change.

**Comment by schellap** [comment]
@gkhanna79, can we merge this change now?

**Comment by gkhanna79** [comment]
Yes, send email to shiproom and then we can merge.

**Pull request merged**
