### PR TITLE
Disable including source files in nupkgs during source-build to work around the long path limitation.

### PR DESCRIPTION
**Pull request by eerhardt**
/cc @weshaggard @ericstj @dagood 

I've logged https://github.com/dotnet/core-setup/issues/3269 to track turning this back on.

### CODE REVIEW

**Comment by ericstj** [comment]
What changed that started breaking this?  I've had to jump through hoops in the past to keep it working: https://github.com/dotnet/core-setup/commit/38565036f3d3c67e873184336528c63c93fce1e8#diff-5e85be3c1f3e808f5c649b7357c3a686

**Comment by eerhardt** [comment]
> What changed that started breaking this?

See https://github.com/dotnet/source-build/pull/206#issuecomment-334028708

Basically we are building this repo nested inside of the `source-build` repo, and the root repo path to core-setup is now: `D:\j\workspace\Windows_NT_Re---a3f4c8f6\src\core-setup\`

**Comment by eerhardt** [comment]
> Back when I hit this the last time folks insisted I keep the source packages working 

Who were the folks?  I'd like to get their thoughts on where we are heading here.

**Comment by ericstj** [comment]
> Who were the folks?

I've forwarded you an email thread with some more context.

**Pull request merged**
