### PR TITLE
[release/1.0.0] Generate hostfxr packages/zips

### PR DESCRIPTION
**Pull request by schellap**
Port of #135

Cc @gkhanna79 @brthor

### CODE REVIEW

**Comment by gkhanna79** [comment]
Fixes https://github.com/dotnet/core-setup/issues/94

**Comment by schellap** [comment]
@dotnet-bot test Windows_NT x64 Release Build please

**Comment by schellap** [comment]
@dotnet-bot Windows_NT x86 Debug Build please

**Comment by schellap** [comment]
@dotnet-bot test Windows_NT x86 Debug Build please

**Comment by schellap** [comment]
@dotnet-bot test Windows_NT x64 Release Build please

**Comment by gkhanna79** [comment]
Windows build failed due to zLib failure:

```
:59:15 Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
18:59:15    at Interop.zlib.deflate(Byte* stream, Int32 flush)
18:59:15    at Interop.zlib.Deflate(ZStream& stream, FlushCode flush)
18:59:15    at System.IO.Compression.Deflater.Deflate(FlushCode flushCode)
18:59:15    at System.IO.Compression.Deflater.ReadDeflateOutput(Byte[] outputBuffer, FlushCode flushCode, Int32& bytesRead)
```

@joshfree @ianhays @stephentoub Is this expected?

**Comment by stephentoub** [comment]
https://github.com/dotnet/corefx/issues/9339

**Comment by ianhays** [comment]
```
18:58:28 Installing dotnet cli...
18:58:30 Restoring BuildTools version 1.0.25-prerelease-00510-02...
```
It is expected. buildtools version 510-02 suffers the issue described in https://github.com/dotnet/corefx/issues/9339 (the clrcompression is old). The buildtools being restored should be [1.0.25-prerelease-00511-02](https://github.com/dotnet/core-setup/pull/147).

**Comment by gkhanna79** [comment]
@eerhardt Can you please update buildTools version for the release branch?

**Comment by eerhardt** [comment]
> @eerhardt Can you please update buildTools version for the release branch?

It was updated last night:  https://github.com/dotnet/core-setup/pull/147

**Comment by eerhardt** [comment]
test Details Windows_NT x64 Release Build

**Comment by eerhardt** [comment]
test Windows_NT x64 Release Build

**Comment by ianhays** [comment]
It looks like this CI build failed before that was merged.

**Comment by gkhanna79** [comment]
Should we just restart the Windows job to pick it up?

**Comment by gkhanna79** [comment]
Please wait on merging this until @joshfree gives the green light!

**Comment by Petermarcu** [comment]
Merging per meeting discussion.

**Pull request merged**
