### PR TITLE
Update badge svg size

### PR DESCRIPTION
**Pull request by Petermarcu**
skip ci please

### CODE REVIEW

**Comment by Petermarcu** [comment]
@gkhanna79 , This is for release/1.1.0. Any reason this can't go in?

**Comment by gkhanna79** [comment]
This should be held off until our next release post RTM.

**Comment by Petermarcu** [comment]
@gkhanna79 , I want it in 1.1.1. Will that be coming from this branch?

**Comment by gkhanna79** [comment]
Yes, but we should merge this commit once we are in the clear for 1.1.0.

**Comment by Petermarcu** [comment]
ok

**Comment by Petermarcu** [comment]
@gkhanna79 , Are we in the clear now?

**Comment by gkhanna79** [comment]
Yes.

**Pull request merged**
