### PR TITLE
Adding FilesToSign error check to all ItemGroups

### PR DESCRIPTION
**Pull request by jcagme**
This error check was added to only one item group. Adding it to all

### CODE REVIEW

**Comment by weshaggard** [comment]
Lets wait until after the current servicing is done before merging.

**Comment by jcagme** [comment]
Changes will be merged until we have stable builds in place. We don't want extra builds being triggered and using the only two agent machines we have in the pool we use for signing just for this change.

**Comment by MattGal** [comment]
@weshaggard  I understand the abundance of caution there but in that case we should make sure to review logs and ensure that signing is happening  (if it's identical to the error last time, the OutDir check _should_ catch it anyways)

**Comment by jcagme** [comment]
@MattGal  since we are using the pool where things "have always worked" signing should work, if not, the OutDir condition , as you mentioned, should catch the error

**Comment by weshaggard** [comment]
>@weshaggard I understand the abundance of caution there but in that case we should make sure to review logs and ensure that signing is happening (if it's identical to the error last time, the OutDir check should catch it anyways)

While I agree the OutDir check would likely catch this as the code currently exists but I think the right check is to verify the item group which helps guard against any future changes to where we might pick-up files. The FilesToSign item group is the true source of things so I like checking that better.

**Comment by eerhardt** [comment]
Can we get these changes in `release/2.0.0` and `master` as well?

**Comment by jcagme** [comment]
> Can we get these changes in release/2.0.0 and master as well?
Sure, will send the PRs shortly. Same as 1.0 and 1.1, feel free to merge when we already have stable packs.

**Comment by eerhardt** [comment]
Can this PR be merged now?

**Comment by MattGal** [comment]
@eerhardt  while I still think it should be:

```
Condition = "'@(FilesToSign->Count())'!='0'" 
```
... for readability, this is OK to merge as we're not trying to get any release builds out the door currently.

**Pull request merged**
