### PR TITLE
Enable Deb Packages for Ubuntu 16.04

### PR DESCRIPTION
**Pull request by brthor**
Add Ubuntu 16.04 debian packages

Worked with @chuan to get the xenial distribution added to our repo, and have added the appropriate environment variables to our build definition. 

Tested with our test feed, for anyone wanting to try it out (on ubuntu 16.04):
```
sudo sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-dev/ xenial main" > /etc/apt/sources.list.d/dotnetdev.list'
sudo apt-key adv --keyserver apt-mo.trafficmanager.net --recv-keys 417A0893
sudo apt-get update

sudo apt-get install dotnet-sharedframework-microsoft.netcore.app-1.0.0
```

@Petermarcu @piotrpMSFT @ellismg @eerhardt

### CODE REVIEW

**Comment by brthor** [comment]
cc @blackdwarf 

after this is merged, the ubuntu 16.04 packages can be installed like so
```
sudo sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet/ xenial main" > /etc/apt/sources.list.d/dotnetdev.list'
sudo apt-key adv --keyserver apt-mo.trafficmanager.net --recv-keys 417A0893
sudo apt-get update
```

**Comment by ellismg** [comment]
LGTM.  Cool that it mostly just worked!

**Comment by brthor** [comment]
liblldb was the only necessary addition, that was pretty nice!

**Comment by eerhardt** [comment]
:shipit: This look so much better.

**Comment by brthor** [comment]
Looks like the jenkins build is not on docker

**Comment by blackdwarf** [comment]
Hmmm...this means another version of Ubuntu in Getting Started. This is a must I presume @brthor ?

**Comment by brthor** [comment]
netci changes in #164

**Comment by brthor** [comment]
@blackdwarf this is technically using the current feed but notice the distribution `trusty` changed to `xenial`. This is the recommended way to go about things as I understand it.

**Comment by blackdwarf** [comment]
Ah, so all else is the same. Yeah, saw it now. OK, good.

**Comment by brthor** [comment]
@blackdwarf just be careful not to use the `dotnet-dev` feed 😄

**Comment by brthor** [comment]
@dotnet-bot test this please

**Comment by brthor** [comment]
@dotnet-bot test Ubuntu16.04 x64 Release Build please

**Comment by brthor** [comment]
Strange unrelated test failure on fedora

```
Microsoft.DotNet.CoreSetup.Test.HostActivation.StandaloneApp.GivenThatICareAboutStandaloneAppActivation.Running_Build_Output_Standalone_EXE_with_DepsJson_and_RuntimeConfig_Local_Succeeds [FAIL]
21:28:25       Expected command to pass but it did not.
21:28:25       File Name: /mnt/resource/j/workspace/dotnet_core-setup/release_1.0.0/debug_fedora23_x64_prtest/artifacts/fedora.23-x64/tests/artifacts/2/StandaloneApp/bin/StandaloneApp
21:28:25       Arguments: 
21:28:25       Exit Code: 26
```

**Comment by brthor** [comment]
@dotnet-bot test Fedora23 x64 Debug Build please

**Comment by eerhardt** [comment]
> Strange unrelated test failure on fedora

whoa. I've never seen that one before.

**Comment by brthor** [comment]
packages are live 👍 

```
Setting up dotnet-host (1.0.1-1) ...
Setting up dotnet-hostfxr-1.0.1 (1.0.1-1) ...
Setting up dotnet-sharedframework-microsoft.netcore.app-1.0.0 (1.0.0-1) ...
root@c0f6f032d3e7:/opt/code/core-setup#
```

**Pull request merged**
