### PR TITLE
Re-enable symbol publishing with new uploader package.

### PR DESCRIPTION
**Pull request by mikem8361**

### CODE REVIEW

**Comment by weshaggard** [comment]
The changes look good but I cannot say if they will work or not without knowing that is changed in the package. What verification have you done?

**Comment by mikem8361** [comment]
I’ve done local testing but as you know my local environment isn’t the same as the build lab.  My changes (in the new package version) include a new desktop uploader build task and all the necessary dependencies.

I didn’t think it would work, but I tried to queue the DotNet-Core-Setup-Master-3160_Core-Setup-Publish using a branch with my changes in the DotNet-Core-Setup-Trusted repo.  It failed on the “Clone tools” step with “Authentication failed for 'https://dn-bot:@devdiv.visualstudio.com/DevDiv/_git/DotNet-BuildPipeline/'”. I guess the PB_VsoPassword isn’t set correctly when I queue a build.

Unless there is a way to run a build before I commit the changes, I’m not sure how to truly verify it.

**Comment by mikem8361** [comment]
@weshaggard, should I go ahead and merge this PR?

**Comment by weshaggard** [comment]
@mikem8361 yes but please queue a build and monitor it. If it fails still be ready to revert.

**Comment by mikem8361** [comment]
How do I properly queue a build? Like my previous messages, I tried queuing DotNet-Core-Setup-Master-3160_Core-Setup-Publish on a branch with my changes. It failed on one of  the early steps cloning the tools.

**Comment by weshaggard** [comment]
I queued a build https://devdiv.visualstudio.com/DevDiv/Net%20CoreFX/_build/index?buildId=1207489&_a=summary.

**Pull request merged**
