### PR TITLE
Fix publish location for hostfxr in Azure

### PR DESCRIPTION
**Pull request by schellap**
@brthor PTAL.

Cc @joshfree Fix publish location for a host component in Azure.

### CODE REVIEW

**Comment by gkhanna79** [comment]
@schellap What is the bug for this that details the problem?

**Comment by gkhanna79** [comment]
And should this be fixed in master as well?

**Comment by schellap** [comment]
@brthor @eerhardt  what is the general policy on the URL format: https://dotnetcli.blob.core.windows.net/dotnet/preview/Binaries/1.0.0/dotnet-hostfxr-win-x86.1.0.1.zip

Specifically,
preview/Binaries/1.0.0 --> Here does the 1.0.0 imply component version or the repo (release) version. It would be confusing to have such a download link like: 

https://dotnetcli.blob.core.windows.net/dotnet/preview/Binaries/1.0.0/dotnet-hostfxr-win-x86.1.0.1.zip

**Comment by schellap** [comment]
@gkhanna79 the bug and the master PR is linked in this PR.

**Comment by gkhanna79** [comment]
Fixes https://github.com/dotnet/core-setup/issues/181

**Comment by gkhanna79** [comment]
@schellap Why do we need to take this fix right now?

**Comment by gkhanna79** [comment]
Does this break anything? @eerhardt Thoughts?

**Comment by schellap** [comment]
@gkhanna79, we can fix this in the blob storage as well for RTM, so no this is not a blocker. It should be fixed in the servicing branch definitely for future packages.

@eerhardt, If we aligned on repo/release version for the container key then, we need to fix few other places to use the right version in the container name.

**Comment by brthor** [comment]
@schellap Nobody is consuming this that I know of, so this should be okay (not breaking) as is.

**Comment by gkhanna79** [comment]
Closing per discussion in https://github.com/dotnet/core-setup/issues/181

**Pull request closed without merging**
