### PR TITLE
Verification test for .NET Runtime and SDK Linux packages

### PR DESCRIPTION
**Pull request by drneve**
README.md for description

### CODE REVIEW

**Comment by drneve** [comment]
@rakeshsinghranchi @eerhardt

**Comment by steveharter** [comment]
Ping @rakeshsinghranchi @weshaggard for review

**Comment by vitek-karas** [comment]
@rakeshsinghranchi  Could you please take a look - the PR has been sitting here for many months now.

**Comment by rakeshsinghranchi** [comment]
This script can be used for setup testing for native Linux installer and is good starting script for manual validation. @leecow can share this script to setup validation team.

**Comment by vitek-karas** [comment]
@rakeshsinghranchi Do we want to merge this then?

**Comment by leecow** [comment]
@richaverma1 to pass along to the validation team.

**Pull request merged**
