### PR TITLE
Publish installers and checksums

### PR DESCRIPTION
**Pull request by mmitche**
- Use the arcade publishing process to publish the installers and checksums
- Remove old blob publishing
- Calculate the product version using an always-suffixed version
- Change the blob path that we should upload to to be Runtime/<version> instead of assets/core-setup/.. to line up with the desired paths.

### CODE REVIEW

**Comment by mmitche** [comment]
Need one additional arcade update, so that we can get sha512 to go to the checksums dir.

**Comment by dagood** [comment]
To link them up--this fixes https://github.com/dotnet/core-setup/issues/8285 (using Arcade publishing) and https://github.com/dotnet/core-setup/issues/8244 (avoiding overwrites on build storage, which ended up still being in our control: Arcade publish is still driven by the repo quite a bit, more than I originally thought).

**Comment by dagood** [comment]
I see now this is to `release/3.0`... mind porting it to `master`?

**Comment by mmitche** [comment]
> I see now this is to `release/3.0`... mind porting it to `master`?

Yeah, was planning on it. Are there still inter-branch merges to master?

**Comment by dagood** [comment]
> Are there still inter-branch merges to master?

There never were, this repo follows the CoreCLR/CoreFX model of making changes in `master` then porting them to the oldest applicable `release` branch, then that flows through to the latest `release` branch.

**Comment by mmitche** [comment]
I'll port this to master after the next arcade update there.

**Pull request merged**
