### PR TITLE
Port sdk resolver changes for VS 15.9 to 2.1

### PR DESCRIPTION
**Pull request by nguerrera**

### CODE REVIEW

**Comment by jamshedd** [comment]
Approved for 2.1.5

**Comment by nguerrera** [comment]
@jamshedd Thanks. Is this branch open for 2.1.5 yet?

**Comment by nguerrera** [comment]
Ping @jeffschwMSFT for code review. 

cc @livarcocc

**Comment by nguerrera** [comment]
CI failure on OS X is in the tests I ported. I will investigate.

**Comment by jamshedd** [comment]
@nguerrera Yes, we're open for 2.1.5, please merge your changes before 9/12.

**Pull request merged**
