### PR TITLE
Remove old build code.

### PR DESCRIPTION
**Pull request by eerhardt**
Move the parts that are still in use into the TestUtils project.

@mellinoe 

/cc @weshaggard @gkhanna79

### CODE REVIEW

**Comment by eerhardt** [comment]
test Ubuntu arm Release Build  

@gkhanna79  - is this broken by your latest change?

**Comment by gkhanna79** [comment]
I think it is - let me try to fix it.

**Comment by gkhanna79** [comment]
I have merged a fix - can you please rebase and retry?

**Comment by gkhanna79** [comment]
@dotnet-bot test this please

**Pull request merged**
