### PR TITLE
Update licence info

### LINKED ISSUE #5224: Use up to date file license headers
Currently lot of the files in this repo use license header like this:
``` C++
// Copyright (c) .NET Foundation and contributors. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
```

Other dotnet repos (coreclr, CoreFx) use header like this:
``` C++
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.
```

### PR DESCRIPTION
**Pull request by Potapy4**
Fixes #5224

### CODE REVIEW

**Comment by danmosemsft** [comment]
cc @richlander just to be sure this is the correct change.

**Comment by Potapy4** [comment]
@richlander just ping 🔔

**Comment by vitek-karas** [comment]
@Potapy4 First of all, a big thanks for doing this!

Can you please rebase, check again that no old license headers sneaked in and if so fix them...

I'll approve it then. Waiting on Rich is … not working :-)
The new license header is the same as in CoreFX/CoreCLR - so it should be good enough for this repo as well.

**Comment by Potapy4** [comment]
> @Potapy4 First of all, a big thanks for doing this!
> 
> Can you please rebase, check again that no old license headers sneaked in and if so fix them...
> 
> I'll approve it then. Waiting on Rich is … not working :-)
> The new license header is the same as in CoreFX/CoreCLR - so it should be good enough for this repo as well.

I updated the missing file headers 📜

**Comment by vitek-karas** [comment]
Sorry - I didn't make it in time - can you rebase again please - there are still some conflicts...

**Pull request merged**
