### PR TITLE
Remove global location lookup support using PATH in non Windows

### PR DESCRIPTION
**Pull request by steveharter**
Remove support for global location lookup based on PATH for Linux\Mac

Direct port of PR https://github.com/dotnet/core-setup/pull/2633, commit https://github.com/dotnet/core-setup/commit/ad495acf4c74e4577c7de8158aa42d518bdc1c18

For issue #2611

### CODE REVIEW

**Comment by steveharter** [comment]
test Windows_NT x64 Release Build

```
D:\j\workspace\release_windo---c83e2cfa\Tools\packageresolve.targets(42,5): error MSB3073: The command ""D:\j\workspace\release_windo---c83e2cfa\Tools/dotnetcli/dotnet.exe" restore --packages "D:\j\workspace\release_windo---c83e2cfa\packages" --source https://dotnet.myget.org/F/dotnet-core/api/v3/index.json --source https://dotnet.myget.org/F/cli-deps/api/v3/index.json --source https://dotnet.myget.org/F/dotnet-buildtools/api/v3/index.json --source https://www.myget.org/F/nugetbuild/api/v3/index.json --source https://api.nuget.org/v3/index.json --source https://dotnet.myget.org/F/dotnet-corefxlab/api/v3/index.json D:\j\workspace\release_windo---c83e2cfa\src\pkg\projects\Microsoft.NETCore.UniversalWindowsPlatform\src\Microsoft.NETCore.UniversalWindowsPlatform.depproj /p:TargetGroup= /p:ConfigurationGroup=Release /p:ArchGroup= /p:OSGroup=Windows_NT /p:TargetFramework=uap10.1 -r win10-x64-aot /p:HasRuntimePackages=false /p:IntermediateOutputPath=D:\j\workspace\release_windo---c83e2cfa\Bin/obj/win-x64.Release\Microsoft.NETCore.UniversalWindowsPlatform\win10-x64-aot/win10-x64-aot" exited with code 1. [D:\j\workspace\release_windo---c83e2cfa\src\pkg\projects\Microsoft.NETCore.UniversalWindowsPlatform\src\Microsoft.NETCore.UniversalWindowsPlatform.depproj]
```

**Comment by Petermarcu** [comment]
@gkhanna79 do we need this in Preview2? Can you help assess the risk? Looks like a very straight forward change. Do we expect this to break people?

**Comment by gkhanna79** [comment]
@eerhardt and I have gone over the change and this is the one I discussed in shiproom last Thursday. 

IMHO, we should take this change right now, as opposed to RTM. We do not anticipate any fallout since no one is expecting to have notion of "global install location" to be consistent/present for non-Windows.

Also, this behavior (being removed) was introduced only in 2.0 earlier this year (around Feb), so it is not a regression from 1.x.

@eerhardt Do you want to add/correct anything since you have investigated this area?

**Comment by eerhardt** [comment]
> Do you want to add/correct anything since you have investigated this area?

The only thing I'd add is that we don't have a high priority user-scenario for this functionality. So it is better to not have it until we have a solid requirement for it.  Than to have it wrong, and try to change it later.

**Comment by gkhanna79** [comment]
Merging this change to take for 2.0.0 Preview2.

**Pull request merged**
