### PR TITLE
use docker for ubuntu 16 jenkins builds

### PR DESCRIPTION
**Pull request by brthor**
@livarcocc Any reason they weren't using docker?

cc @eerhardt 

This is a must for #163 to pass Jenkins tests

### CODE REVIEW

**Comment by brthor** [comment]
This PR broke ubuntu16.04 builds because docker isn't available on our CI machines. Reverting this until we get docker.

cc @livarcocc @mmitche

**Comment by mmitche** [comment]
Docker is available on 14.04.

@brthor Do you remember the specific docker configuration required for 14.04? I seem to remember that we had to change around where images go, etc. to avoid out of disk space issues.

**Comment by mmitche** [comment]
@brthor What's the time sensitivity on this?

**Comment by brthor** [comment]
@mmitche We worked around this in Jenkins CI, not immediately needed but will be good to get it for better coverage. 

We had to change the docker_opts I'll figure out the string we need, what is the `/mnt` path in those machines?

**Comment by mmitche** [comment]
I checked the 14.04 configuration, and that was the only real change.  I'm not sure what the mount location on 16.04 is (it's either /mnt or /mnt/resource)

**Pull request merged**
