### PR TITLE
Enable Host to carry shared component (registry and files) 

### PR DESCRIPTION
**Pull request by rakeshsinghranchi**
This PR fixes a part of issue https://github.com/dotnet/core-setup/issues/1408 . 

IF a newer host is installed, an older host should add to the ref count and claim success . 

**Broken scenario :**
Install Runtime Bundle 2 ( higher version ) 
Install Runtime Bundle 1 ( lower version )
Uninstall Runtime Bundle 2 

Expected result :
-- Host (dotnet.exe) from Bundle2 should exist 
Actual result:
-- Host ( dotnet.exe) is removed

Issue: As of today , Host MSIs are major upgradable ( sharing same keypath and upgrade code ) . This is causing uninstallation of the previously installed lower version of the product. Also, bundle carrying host msi ( Runtime or SDK) skips installation of the lower version host and thus doesn't add the refcount to the component. 

This fix updates the upgrade code for every build and ensures that regkeys are part of shared component too so that only higher version payloads ( dotnet.exe,regkey entry for version ) are preserved during SxS installation.

Similar, fix needs to be made in 1.0 and 1.1 release branch. 

Scenario verified and passed  : 

Build two version of 2.0 runtime bundles locally and tested the following scenario
Bundle1 : lower version
Bundle 2 : higher version

Scenario:
Scenario 1:
1.	Install Bundle 1 
2.	Install Bundle 2
3.	Verify bundle installed under program files 
4.	Verify bundle.exe under program files\dotnet\ has version from bundle2
5.	Verify the registry key has version from Bundle 2 
6.	Open a command prompt and run dotnet.exe from anywhere ( dotnet.exe path should be present in the system path variable )
7.	Uninstall Bundle 2 
8.	Verify Bundle 2 versioned dotnet.exe and *.txt files remain in the machine and registry key has bundle 2 version 
9.	Verify dotnet.exe remains in the path environment variable
10.	Uninstall Bundle 1
11.	Verify all artifacts of Bundle 1 and Bundle 2 are removed from machine
12.	Verify dotnet.exe is removed from path environment

Scenario 2 
1.	Install Bundle 2
2.	Install Bundle 1
3.	Verify bundle is installed under program files ( focus on program files\donet.exe and license.txt , thirdpartynotices.txt ) . Verify that dotnet.exe and registry key has Bundle 2 version
4.	Open a command prompt and run dotnet.exe from anywhere ( dotnet.exe path should be present in the system path variable )
5.	Uninstall Bundle 2
a.	Verify dotnet.exe and .txt files still exist in the machine
b.	Verify Registry key value still has Bundle 2 version
6.	Uninstall Bundle 1
a.	Verify all runtime artifacts are removed from machine
b.	Verify dotnet.exe is removed from path environment

### CODE REVIEW

**Comment by gkhanna79** [comment]
> Similar, fix needs to be made in 1.0 and 1.1 release branch.

Can you please file an issue to track this?

**Comment by gkhanna79** [comment]
@rakeshsinghranchi Can you also validate Scenario 1 and 2 where lower version comes from 1.0.X and 1.1.x and higher is from 2.0?

**Comment by gkhanna79** [comment]
Overall, looks fine to me.

@Petermarcu Can you PTAL as well?

**Comment by rakeshsinghranchi** [comment]
I have covered below scenario :

Scenario 3 : 
1.Install 1.0.x runtime
2.Install 2.0.0 private runtime
3.Uninstall 2.0.0 private runtime
   --verify :
        1.  2.0.0 host remains in the machine 
        2. Version regkey has 2.0.0 value for HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\sharedhost\Version
4.Uninstall 1.0.x runtime
    --verify : all install artifacts are removed from machine .
**Result : Passed ,** 

Scenario 4:
1.Install 2.0.0 private runtime 
2.Install 1.0.x runtime 
   --Verify : 
                1. 2.0.0 host remains in the machine 
                2. Version regkey has 1.0.x value HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\sharedhost\Version ( This is an issue because regkey is not part of shared component in 1.0.x 
3.Uninstall 2.0.0 private runtime 
        -- Verify:
              1. 2.0.0 host remains in the machine
              2. Version regkey has 1.0.x value
4.Uninstall 1.0.x runtime

**Comment by gkhanna79** [comment]
Does Scenario 4 pass as well?

**Comment by rakeshsinghranchi** [comment]
Scenario 4 passes partially. Registry key for version value is overwritten by 1.0.x bundle as it's not part of shared component.

**Comment by gkhanna79** [comment]
> Registry key for version value is overwritten by 1.0.x bundle as it's not part of shared component.

So, this would be an issue we need to fix for 1.0.x and 1.1.x, right? If so, can you please file issues for them.

I would also suggest that you make the changes locally for 1.0.x and 1.1.x and confirm that they work with this change as expected.

**Comment by rakeshsinghranchi** [comment]
@vivmishra  will port fixes to 1.0 and 1.1 . Vivek, please file separate issues.

**Comment by Petermarcu** [comment]
LGTM

**Pull request merged**
