### PR TITLE
Update UWP MP to 5.2.3

### PR DESCRIPTION
**Pull request by zamont**
- Change the version on Microsoft.NETCore.UniversalWindowsPlatform.pkgproj
- Edit project.json to pick up new Serialization libraries, add libraries whose dependencies were not stated in MP 5.2.2, and bump down the dependency on Microsoft.NETCore.Runtime.CoreCLR to 1.0.3 to match the version that MP 5.2.2 depends on
- Fixes dotnet/corefx#10338

### CODE REVIEW

**Comment by gkhanna79** [comment]
Please also update https://github.com/dotnet/core-setup/blob/release/1.0.0/pkg/projects/packages.builds#L15 to enable it to build UWP metapackage as well for the next servicing release.

CC @weshaggard @leecow

**Comment by weshaggard** [comment]
>Please also update https://github.com/dotnet/core-setup/blob/release/1.0.0/pkg/projects/packages.builds#L15 to enable it to build UWP metapackage as well for the next servicing release.

Given that we are building it manually I don't think we want to add it there.

**Comment by zamont** [comment]
@gkhanna79 do I have permission to merge?

**Comment by gkhanna79** [comment]
Yes, you can merge @zamont. I presume this change corresponds to what you pushed yesterday?

**Comment by zamont** [comment]
Yes, this corresponds with the 5.2.3 MP package that was pushed yesterday. I will perform the merge now.

**Pull request merged**
