### PR TITLE
[WIP] Stabilize for 1.1.2

### PR DESCRIPTION
**Pull request by gkhanna79**
Stabilize packages for 1.1.2

### CODE REVIEW

**Comment by gkhanna79** [comment]
@eerhardt PTAL

Failures in CI are expected.

**Comment by eerhardt** [comment]
Do you need to update the branchinfo.txt like you are in https://github.com/dotnet/core-setup/pull/2028/files?

**Comment by gkhanna79** [comment]
There are slight differences in the two branches and I have noticed that it was not changed earlier as well, and pre-release suffix was omitted as expected.

Overall, I think we should simplify a lot of complexity in this infrastructure :(

**Comment by eerhardt** [comment]
> Overall, I think we should simplify a lot of complexity in this infrastructure :(

Agreed.  We have already taken a huge leap forward here in the dotnet/cli repo when we moved to MSBuild.  Hopefully we can do the same when this repo is converted.

**Pull request closed without merging**
