### PR TITLE
Increase timeout for acquiring lease from 1 to 5 minutes

### PR DESCRIPTION
**Pull request by wtgodbe**
This should solve the 'lease expired' issue in the Windows signing jobs.

### CODE REVIEW

**Comment by wtgodbe** [comment]
CC @dagood @gkhanna79 @brthor (we should have this for master as well as release/1.1.0)

**Comment by gkhanna79** [comment]
Thanks for making this change. We should merge this once we have confirmed it works in release/1.1.0.

**Comment by gkhanna79** [comment]
LGTM

**Comment by brthor** [comment]
:shipit:

**Pull request merged**
