### PR TITLE
[release/2.1] Add Tizen 5.0 RID

### PR DESCRIPTION
**Pull request by gbalykov**
Port from master: #4332 

cc @alpencolt @Dmitri-Botcharnikov

### CODE REVIEW

**Comment by gbalykov** [comment]
@eerhardt could this be merged? 
Related PR for CoreFX: https://github.com/dotnet/corefx/pull/30640, https://github.com/dotnet/corefx/pull/30888

**Comment by eerhardt** [comment]
@weshaggard @danmosemsft @leecow - does this need to go through shiproom approval since it is a change to `release/2.1`?

**Comment by karelz** [comment]
@gbalykov is it port from master? Can you please link it?

**Comment by gbalykov** [comment]
@karelz I've updated description of PR

**Comment by leecow** [comment]
We talked about this in shiproom Tues and are good with this. cc @Petermarcu

**Comment by eerhardt** [comment]
@dotnet-bot test this please

**Pull request merged**
