### PR TITLE
Introduce rootfs for cross-compilation

### PR DESCRIPTION
**Pull request by hqueue**
skip ci please

Introduce rootfs for cross compilation.  I've added scripts for ARM and ARM softfp.
Tested it with `sudo ./cross/build-rootfs.sh arm` and  `sudo ./cross/build-rootfs.sh arm-softfp` as documented in https://github.com/dotnet/coreclr/blob/master/Documentation/building/cross-building.md to keep consistency with CoreCLR and CoreFX.

Basically the code has been imported from CoreCLR and remove x86 and arm64.
rootfs is exactly same with CoreCLR, i.e. we can also build CoreCLR with this rootfs too.
Later we can refine rootfs to reduce size only with required packages if necessary.
BTW CoreFX has a different configuration.

### CODE REVIEW

**Comment by hqueue** [comment]
CC @schellap @ramarag @janvorli @gkhanna79 @kouvel PTAL

Related issue: #729

**Comment by gkhanna79** [comment]
> Basically the code has been imported from CoreCLR and remove x86 and arm64

I was thinking about this. Since there is work going on to bring Linux for x86 (https://github.com/dotnet/coreclr/issues/8188), you may just want to keep the x86 support as well (but do not need to test it).

Aside from this, LGTM.

**Comment by hqueue** [comment]
CC @gkhanna79  @schellap @ramarag  I've added x86 rootfs as suggested.

**Comment by gkhanna79** [comment]
LGTM - assuming you have validated it, right?

**Comment by hqueue** [comment]
@gkhanna79 Right, we have test several this PR #747 and PR #749  together and it works for ARM :)

**Pull request merged**
