### PR TITLE
Add PlatformManifest props to NETCore.App

### PR DESCRIPTION
**Pull request by ericstj**
This data informs the conflict resolution task what files make up the
shared framework, and what their versions are.  This is used to
determine if files from packages should be copied local or not.

/cc @weshaggard @terrajobst @eerhardt

### CODE REVIEW

**Comment by ericstj** [comment]
Looks like core-setup isn't in a great state to use buildtools to build CS from pkg.  I'll see what I can do to fix this.  /cc @AlfredoMS

**Comment by weshaggard** [comment]
What is the size of the generated file now?

**Comment by ericstj** [comment]
10KB

**Comment by ericstj** [comment]
Windows CI is now failing with
```
CSC : error CS0041: Unexpected error writing debug information -- 'Windows PDB writer is not available -- could not find Microsoft.DiaSymReader.Native.amd64.dll' [D:\j\workspace\release_windo---c6d433cb\pkg\tasks\core-setup.tasks.csproj]
```
@weshaggard @joperezr : something I'm missing from init-tools?

**Comment by ericstj** [comment]
Looks like this is caused by this issue: https://github.com/dotnet/cli/issues/1433
Apparently our CI machines don't have VC redist.
I'm looking at updating the CLI we're using to workaround this.

**Comment by ericstj** [comment]
Closing this, will reopen against master.

**Pull request closed without merging**
