### PR TITLE
Upgrade to BuildTools 2.0.0-prerelease-01726-03.

### PR DESCRIPTION
**Pull request by ravimeda**
Get the latest fixes for BuildTools.

@chcosta @dagood PTAL.

### CODE REVIEW

**Comment by chcosta** [comment]
LGTM pending ci

**Comment by ravimeda** [comment]
@mmitche what causes this error in CI? Please clarify..

```
D:\j\workspace\release_windo---0c55dee9\src\sharedFramework\sharedFramework.proj(126,5): error MSB4018: The "ProcessSharedFrameworkDeps" task failed unexpectedly.
11:52:07 D:\j\workspace\release_windo---0c55dee9\src\sharedFramework\sharedFramework.proj(126,5): error MSB4018: System.IO.FileNotFoundException: Could not load file or assembly 'NuGet.RuntimeModel, Version=3.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.

**Comment by dagood** [comment]
The [NuGet nuget package](https://github.com/dotnet/core-setup/blob/cd4b109ac38a8558ee6e8799540ab280976664ac/tools-local/tasks/core-setup.tasks.csproj#L29) probably needs to be upgraded from 3.5.0. My NuGet upgrade to 4.3.0-preview2-4095 in BuildTools (https://github.com/dotnet/buildtools/pull/1556) is probably the cause.

**Comment by mmitche** [comment]
@ravimeda No idea, i'm guessing dependencies aren't set correctly?

**Comment by mmitche** [comment]
Missing nuget package perhaps?

**Comment by ravimeda** [comment]
Thanks @mmitche and @dagood. Updating NuGet.ProjectModel seems to have clear CI. 4f31047

**Pull request merged**
