### PR TITLE
Added what TPA is.

### PR DESCRIPTION
**Pull request by jaliyaudagedara**
Added the descriptive name for TPA.

### CODE REVIEW

**Comment by vitek-karas** [comment]
@dotnet-bot test OSX x64 Release Build

**Comment by sbomer** [comment]
LGTM, thanks! While we're at it I fixed another typo I noticed.

**Comment by jaliyaudagedara** [comment]
Awesome, thanks guys!

**Comment by jaliyaudagedara** [comment]
I am sorry, thought it's merged. Reopened.

**Comment by vitek-karas** [comment]
@dotnet-bot test OSX x64 Release Build

**Pull request merged**
