### PR TITLE
Update Tizen CI docker image

### PR DESCRIPTION
**Pull request by gbalykov**
Update Tizen CI docker image to ubuntu 16.04

Related issue: dotnet/corefx#28901

cc @Dmitri-Botcharnikov @alpencolt

### CODE REVIEW

**Comment by gbalykov** [comment]
@dotnet-bot test Tizen armel Cross Release Build

**Comment by gbalykov** [comment]
@dotnet-bot help

**Comment by gbalykov** [comment]
@dotnet-bot test Linux-musl x64 Debug Build

**Comment by gbalykov** [comment]
@dotnet-bot test this please

**Comment by gbalykov** [comment]
@dotnet-bot test ci please

**Comment by gbalykov** [comment]
@weshaggard, could this be merged? same PR for CoreCLR (https://github.com/dotnet/coreclr/pull/17814) is in master now

**Comment by weshaggard** [comment]
Yes I'm good with it merging. If we see any issues around it I will ping you guys.

**Pull request merged**
