### PR TITLE
Create framework assembly list file in .NET Core targeting pack

### PR DESCRIPTION
**Pull request by dagood**
This adds `data/FrameworkList.xml` to the targeting pack with contents like this:

```xml
<FileList Name=".NET Core 3.0" TargetFrameworkIdentifier=".NETCoreApp" TargetFrameworkVersion="3.0" FrameworkName="Microsoft.NETCore.App">
  <File AssemblyName="Microsoft.CSharp" PublicKeyToken="b03f5f7f11d50a3a" AssemblyVersion="4.0.0.0" FileVersion="4.7.19.11304" />
  <File AssemblyName="Microsoft.VisualBasic.Core" PublicKeyToken="b03f5f7f11d50a3a" AssemblyVersion="10.0.4.0" FileVersion="4.7.19.11304" />
  <File AssemblyName="Microsoft.VisualBasic" PublicKeyToken="b03f5f7f11d50a3a" AssemblyVersion="10.0.0.0" FileVersion="14.7.3060.0" />
  <File AssemblyName="Microsoft.Win32.Primitives" PublicKeyToken="b03f5f7f11d50a3a" AssemblyVersion="4.1.1.0" FileVersion="4.7.19.11304" />
  <File AssemblyName="mscorlib" PublicKeyToken="b77a5c561934e089" AssemblyVersion="4.0.0.0" FileVersion="4.7.3060.0" />
  <File AssemblyName="netstandard" PublicKeyToken="cc7b13ffcd2ddd51" AssemblyVersion="2.1.0.0" FileVersion="1.1.19.7403" />
...
```

This is for https://github.com/dotnet/core-setup/issues/5074.

It might make more sense to name it `Microsoft.NETCore.App.Ref.FrameworkList.txt`, like the platform manifest--just went with what I first heard since I don't think there's a spec for this yet.

@dsplaisted @nguerrera

### CODE REVIEW

**Comment by dsplaisted** [comment]
The path/name for the file look good to me. I think we will eventually want the platform manifest to be `data/PlatformManifest.txt`.

**Comment by dagood** [comment]
No time like the present--renamed the platform manifest.

**Comment by nguerrera** [comment]
In that spirit, we're leaving ref/tfm for the actual reference assemblies as discussed yesterday...

**Comment by dagood** [comment]
Changing the package layout is as simple as removing a target that moves stuff from `ref/` to `data/`, but it has some ripple effects so I'll work on that in another PR.

**Pull request merged**
