### PR TITLE
Add CPD strict dependencies for dotnet/wpf

### PR DESCRIPTION
**Pull request by mmitche**

### CODE REVIEW

**Review by wtgodbe — APPROVED** [review]
This is good, but again let's hold off until we build October since core-setup -> WPF/Winforms is a back edge.

**Comment by wtgodbe** [comment]
This also raises the question of back-edges in 3.1 - currently those never get fired off. We could make it policy to do so at the start of each build window, but when I've done this in the past I often ran into new classes of build failures in those PRs that we didn't wind up resolving because the back-edges were "lower priority".

We could start doing this again for the next patch to see what happens, at least (CC @silvioguiso @Anipik @lukas-lansky). This will also become an issue for 5.0 once it goes into servicing

**Comment by mmitche** [comment]
> This is good, but again let's hold off until we build October since core-setup -> WPF/Winforms is a back edge.

Can I check this in but not trigger the back edge?

**Comment by wtgodbe** [comment]
> Can I check this in but not trigger the back edge?

Well, checking into core-setup at all still fires off all of the core-setup 'front-edges'. In this case it's fine, though - I forgot we're still waiting on a WPF-int change, so checking into this repo won't lose us any time

**Comment by mmitche** [comment]
We'll need to, to be able to turn on CPD strict.

**Comment by wtgodbe** [comment]
> We'll need to, to be able to turn on CPD strict.

@mmitche what are the exact requirements there? Do the back edges need to get exactly the versions we shipped in the previous release? If so, that could be a very manual process. If the versions just need to be "close enough" (e.g. whatever the latest is right before we do branding updates, even if somebody happened to merge something early), then that's straightforward enough.

**Comment by mmitche** [comment]
The versions just need to be close enough such that they are propagating this change.

**Pull request merged**
