### PR TITLE
Adding Arm64 Linux build to Build list

### PR DESCRIPTION
**Pull request by Petermarcu**
- Please add a description for changes you are making.
- If there is an issue related to this PR, please add a reference to it.
- If this PR should not run tests please add say skip_ci_please in this description replacing the underscores with spaces.

### CODE REVIEW

**Comment by sdmaclea** [comment]
`arm64hf` whatr does the `hf` suffix mean?

**Comment by Petermarcu** [comment]
hard floating point as opposed to soft. I just copied what was in the arm32 one. Is it not correct?

**Comment by Petermarcu** [comment]
Should it just stay "armhf"?

**Comment by sdmaclea** [comment]
I do not see that nomenclature used in the arm64 linux world.

Probably because floating point support is required except with special permission from Arm.

**Comment by sdmaclea** [comment]
I think it should just say `arm64`

**Comment by Petermarcu** [comment]
Ok, I don't know why we have armhf for the arm32 build. I can just omit that for now.

**Comment by sdmaclea** [comment]
Arm32 floating point was very optional.

**Comment by Petermarcu** [comment]
Sounds good. I made the change.

**Comment by Petermarcu** [comment]
Doesn't impact tests so merging now :)

**Pull request merged**
