### PR TITLE
Enable WinArm32 build

### PR DESCRIPTION
**Pull request by gkhanna79**
This change enables building Core-Setup for WinArm32. 

@schellap @ianhays PTAL

### CODE REVIEW

**Comment by gkhanna79** [comment]
Blocked on https://github.com/dotnet/core-setup/pull/462.

CC @weshaggard

**Comment by weshaggard** [comment]
LGTM - What is blocking this?

**Comment by gkhanna79** [comment]
@weshaggard The failures like the one below are the ones you are working to get fixed in your PR:

`x64/tests/artifacts/2/StandaloneApp/bin/StandaloneApp Arguments: Exit Code: 134 StdOut: StdErr: Unhandled Exception: System.TypeLoadException: Could not load type 'System.IO.TextWriter' from assembly 'System.IO, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. at System.Console.WriteLine(String value) at StandaloneApp.Program.Main(String[] args)`

Once your PR merges, I will rebase against it to ensure this is green and then merge.

**Comment by weshaggard** [comment]
Ah yes. that is triggered by you taking the newer CoreCLR package which isn't backwards compatible with 1.0. We are currently blocked on getting an updated CLI to fix this correctly.

**Comment by gkhanna79** [comment]
Closing in favor of https://github.com/dotnet/core-setup/pull/526

**Pull request closed without merging**
