### PR TITLE
Add links to daily builds

### PR DESCRIPTION
**Pull request by gkhanna79**
@Petermarcu PTAL

CC @wtgodbe

### CODE REVIEW

**Comment by gkhanna79** [comment]
Fixes https://github.com/dotnet/core-setup/issues/544

**Comment by Petermarcu** [comment]
We lost the link on the badges to the SHA that matches the version.

**Comment by Petermarcu** [comment]
Many of these options have native installers as well as archives. Should we provide archive links as well? I think so.

**Comment by Petermarcu** [comment]
The Ubuntu links look funny. Can we format them as rows inside the cell?

**Pull request merged**
