### PR TITLE
[master] Update buildtools to add Serviceable to nupkgs

### PR DESCRIPTION
**Pull request by ericstj**
Updates buildtools to bring changes to write Serviceable element in nuspecs.

/cc @gkhanna79 @schellap @joshfree @weshaggard

### CODE REVIEW

**Comment by ericstj** [comment]
@dotnet-bot test Ubuntu x64 Release Build

**Comment by weshaggard** [comment]
:+1:

**Comment by weshaggard** [comment]
@dotnet-bot test Ubuntu x64 Release Build

**Comment by eerhardt** [comment]
test Ubuntu x64 Release Build

This should be fixed in the latest with #115

**Pull request merged**
