### PR TITLE
Automatic updating of buildtools version.

### PR DESCRIPTION
**Pull request by eerhardt**
Adding support to update buildtools version automatically.

### CODE REVIEW

**Comment by eerhardt** [comment]
hmm, not sure why there aren't any test jobs running.

**Comment by dagood** [comment]
GitHub's behind on delivering web hooks right now: https://status.github.com/

**Comment by eerhardt** [comment]
> I assume you already made the necessary changes to the build definition to start publishing BuildTools to versions?

Yup.  The first one went off without a hitch.  https://github.com/dotnet/versions/commit/7c9088cd9078e1d90be01eb94a3f66ba0a33c9f4#diff-e09f0196db4a2d9236a06099858a4f13

**Comment by eerhardt** [comment]
OSX passed, if you look at the console output in Jenkins.  Not sure why it doesn't show green here.

Merging.

**Pull request merged**
