### PR TITLE
Update BuildTools to 1.0.27-prerelease-01526-01

### PR DESCRIPTION
**Pull request by eerhardt**
@chcosta @weshaggard

### CODE REVIEW

**Comment by weshaggard** [comment]
LGTM - Can you call out what fix you are wanting in this update? Or are you just trying to update to the lastest?

Also @mellinoe I assume we still plan to update to the 2.0.0 version once we get all the projects updated.

**Comment by mellinoe** [comment]
@weshaggard Yes, I'm going to start working on that final part today.

**Comment by eerhardt** [comment]
This is pre-emptive "get on the latest 1.0.27 build".  I was starting to remove our project.json usages in `src\pkg\projects`, and looking at the corefx change that did this: https://github.com/dotnet/corefx/pull/18035, that required a new build-tools version.  So I wanted to update buildtools by itself to ensure updating doesn't break us.

@mellinoe - can you sync with me when you get a chance?

**Comment by eerhardt** [comment]
Closing in favor of #2373

**Pull request closed without merging**
