### PR TITLE
Add support for ProgID registration (3.0)

### PR DESCRIPTION
**Pull request by AaronRobinsonMSFT**
#### Description
Add support for registering a ProgID when a COM class is registered. This only represents the registration part of the work. There is still work to be done in the SDK to generate a .clsidmap file containing a ProgID - https://github.com/dotnet/sdk/pull/3506.

See PR #7551 for post-3.0 release.

#### Customer Impact
Without this support consumption of COM classes in languages that don't have `GUID` support is impossible.

Fixes: dotnet/coreclr#25966
Related: https://github.com/dotnet/coreclr/issues/25946

#### Regression?
COM support is new in 3.0 so this is not a regression from a previous .NET Core release, but is a regression in COM support from .NET Framework using the `RegAsm` tool.

#### Risk
Minimal. The registration of ProgIDs is ignored if not requested (backwards compat with previous Preview releases) and registration is following specific COM semantics for mapping a ProgID and `CLSID` which means there is no impact on any specific .NET Core path.

### CODE REVIEW

**Comment by AaronRobinsonMSFT** [comment]
cc @MeiChin-Tsai @jeffschwMSFT

**Comment by wtgodbe** [comment]
Branch is open, feel free to merge once this is approved by tactics (CC @danmosemsft in case I forget to bring up core-setup tomorrow)

**Comment by AaronRobinsonMSFT** [comment]
This has been approved from the CoreCLR perspective.

**Comment by danmosemsft** [comment]
Didn't get tactics OK yet - @vitek-karas  is following up

**Comment by jeffschwMSFT** [comment]
@danmosemsft is the tactics approval based in email, or in person?

**Comment by danmosemsft** [comment]
@jeffschwMSFT @vitek-karas was going to start a thread with you / aaron to get an approval by email. (We didn't do it in the meeting as none of us had enough context to discuss it)

**Pull request merged**
