### PR TITLE
Adding Roslyn as a dependency to core-setup.

### PR DESCRIPTION
**Pull request by eerhardt**
Fixing stage0 location in update-dependencies.ps1.

@brthor @livarcocc

### CODE REVIEW

**Comment by eerhardt** [comment]
test Ubuntu x64 Release Build

**Comment by livarcocc** [comment]
:shipit:

Also, what do we need to do to not get the friendly neighborhood message?

**Comment by eerhardt** [comment]
> Also, what do we need to do to not get the friendly neighborhood message?

When I first came on the CLI team, DNFBOT did the same thing to me for weeks.  I traded many emails with @martinwoodward @terrajobst @leecow and CLA Automation, and .NET OSS Admins.  Nobody solved it, from my understanding.  And then one day it stopped happening to me.

I assume it is a problem with the CLA automation hook, but I have no idea.  Hoping it works itself out (or someone tagged knows how to fix it).

**Comment by terrajobst** [comment]
@livarcocc @eerhardt 

Sorry for the late reponse. Haven't been going through my GitHub notifications for a while :-) I've reached out internally to see who owns it. I agree that we should tone it down. It's way too noisy.

**Pull request merged**
