### PR TITLE
Add 3pn entry for C++ SDK

### PR DESCRIPTION
**Pull request by richlander**

### CODE REVIEW

**Comment by eerhardt** [comment]
@richlander, for my information, where do we use the C++ REST SDK?

**Comment by ellismg** [comment]
@eerhardt We vendor in parts of it (mainly the JSON parsing stuff) in the native host pieces:

```
matell@matell-ub:~/git/core-setup/src$ git grep cpprestsdk
corehost/cli/json/casablanca/include/cpprest/asyncrt_utils.h:* For the latest on this and related APIs, please see: https://github.com/Microsoft/cpprestsdk
corehost/cli/json/casablanca/include/cpprest/details/basic_types.h:* For the latest on this and related APIs, please see: https://github.com/Microsoft/cpprestsdk
corehost/cli/json/casablanca/include/cpprest/details/cpprest_compat.h:* For the latest on this and related APIs, please see: https://github.com/Microsoft/cpprestsdk
corehost/cli/json/casablanca/include/cpprest/details/nosal.h:* For the latest on this and related APIs, please see: https://github.com/Microsoft/cpprestsdk
corehost/cli/json/casablanca/include/cpprest/json.h:* For the latest on this and related APIs, please see: https://github.com/Microsoft/cpprestsdk
corehost/cli/json/casablanca/include/stdafx.h:* For the latest on this and related APIs, please see: https://github.com/Microsoft/cpprestsdk
corehost/cli/json/casablanca/src/json/json.cpp:* For the latest on this and related APIs, please see: https://github.com/Microsoft/cpprestsdk
corehost/cli/json/casablanca/src/json/json_parsing.cpp:* For the latest on this and related APIs, please see: https://github.com/Microsoft/cpprestsdk
corehost/cli/json/casablanca/src/json/json_serialization.cpp:* For the latest on this and related APIs, please see: https://github.com/Microsoft/cpprestsdk
corehost/cli/json/casablanca/src/utilities/asyncrt_utils.cpp:* For the latest on this and related APIs, please see: https://github.com/Microsoft/cpprestsdk
```

**Comment by eerhardt** [comment]
@gkhanna79 @richlander - are we still interested in this change?  It seems important/necessary.

**Comment by gkhanna79** [comment]
I am fine with this change - is there a specific concern?

**Comment by eerhardt** [comment]
No specific concern from me.  The change is a month old.

Unless someone objects, I'll merge this.

**Comment by karelz** [comment]
Looks like we dropped the ball here @eerhardt can you please rebase and merge it?

**Comment by eerhardt** [comment]
On it.

**Pull request merged**
