### PR TITLE
[Arm64/Linux] Do not try to collect test artifacts

### PR DESCRIPTION
**Pull request by sdmaclea**
@eerhardt PTAL

### CODE REVIEW

**Comment by sdmaclea** [comment]
@eerhardt newly generated CI job needs to be enabled and triggered.

**Comment by eerhardt** [comment]
Running now.  Not sure if you can see this or not:

https://ci.dot.net/job/dotnet_core-setup/job/master/job/GenPRTest/job/release_linux_arm64_prtest/3/console

**Comment by eerhardt** [comment]
It passed.  Thanks, @sdmaclea

**Comment by sdmaclea** [comment]
Thanks

**Pull request merged**
