### PR TITLE
Core-Setup on Buildtools

### PR DESCRIPTION
**Pull request by chcosta**
PR for merging Core-Setup on buildtools changes and using this PR to get CI running clean

### CODE REVIEW

**Comment by mmitche** [comment]
@dotnet-bot test ci please

**Comment by chcosta** [comment]
@dotnet-bot test buildtools please

**Comment by chcosta** [comment]
@dotnet-bot test buildtools please

**Comment by chcosta** [comment]
@dotnet-bot test ci please

**Comment by chcosta** [comment]
@dotnet-bot test buildtools please

**Comment by chcosta** [comment]
@dotnet-bot test ci please

**Comment by chcosta** [comment]
@dotnet-bot test buildtools please

**Comment by chcosta** [comment]
@dotnet-bot test ci please

**Comment by chcosta** [comment]
@dotnet-bot test buildtools please

**Comment by chcosta** [comment]
@dotnet-bot test ci please

**Comment by chcosta** [comment]
@dotnet-bot test buildtools please

**Comment by chcosta** [comment]
@dotnet-bot test buildtools please

**Comment by chcosta** [comment]
@dotnet-bot test ci please

**Comment by chcosta** [comment]
@dotnet-bot test buildtools please

**Comment by chcosta** [comment]
@dotnet-bot test ci please

**Comment by chcosta** [comment]
@dotnet-bot test buildtools please

**Comment by chcosta** [comment]
@dotnet-bot test ci please

**Comment by chcosta** [comment]
@dotnet-bot test buildtools please

**Comment by chcosta** [comment]
@dotnet-bot test ci please

**Comment by chcosta** [comment]
@dotnet-bot test buildtools please

**Comment by chcosta** [comment]
@dotnet-bot test ci please

**Comment by chcosta** [comment]
@dotnet-bot test buildtools please

**Comment by chcosta** [comment]
@dotnet-bot test buildtools please

**Comment by chcosta** [comment]
@dotnet-bot test ci please

**Comment by chcosta** [comment]
@dotnet-bot test buildtools please

**Comment by chcosta** [comment]
@dotnet-bot test buildtools please

**Comment by mmitche** [comment]
test buildtools please

**Comment by mmitche** [comment]
test buildtools please

**Comment by chcosta** [comment]
@dotnet-bot test ci please

**Comment by chcosta** [comment]
@dotnet-bot test ci please

**Comment by chcosta** [comment]
test buildtools please

**Comment by chcosta** [comment]
@dotnet-bot test ci please

**Comment by chcosta** [comment]
test buildtools please

**Comment by chcosta** [comment]
@dotnet-bot test ci please

**Comment by chcosta** [comment]
test buildtools please

**Comment by chcosta** [comment]
@dotnet-bot test ci please

**Comment by chcosta** [comment]
test buildtools please

**Comment by chcosta** [comment]
@dotnet-bot test ci please

**Comment by chcosta** [comment]
test buildtools please

**Pull request merged**
