### PR TITLE
Feed task upgrade

### PR DESCRIPTION
**Pull request by jcagme**
`core-setup` publishing has been the longest throughout the repos due to the amount of packages it publishing along with the fact that, since it is not fully on Arcade, uses an old version of the `Microsoft.DotNet.Feed.Task` which doesn't contain the latest Sleet's changes which include several perf improvements.

Today, a `core-setup` publish could take close to two hours (I'd say in average it takes between 1.25-1:5 hours) and that doesn't include the time it waiting to obtain the lock. This is a good example: https://dnceng.visualstudio.com/internal/_build/results?buildId=147786

After using a version which includes the latest Sleet upgrades we see a huge improvement. From https://dnceng.visualstudio.com/internal/_build/results?buildId=147817:

```
Loaded package nuspecs in 171 ms
Obtained feed lock in 01:46:06.9097384
Updated VirtualCatalog in 97 ms
Updated FlatContainer in 2915 ms
Updated PackageIndex in 4063 ms
Updated Registrations in 25183 ms
Updated Search in 33338 ms
Updated AutoComplete in 00:02:31.0135471
Updated all files locally. Total time: 00:02:32.1907269
Files committed: 333 Size: 629.54 MB Total upload time: 61762 ms
Total execution time: 01:49:46.8517853
```

The previous shows that it only took close to 3.5 minutes to publish all 333 files. This one in particular waited 1:46:06 hours to start processing. 

So, by having `core-setup` take this change we'll improve its overall publish performance helping at the same time unblock other repos trying to publish to the `dotnet-core` feed.

### CODE REVIEW

**Comment by jcagme** [comment]
After this is signed off I'll apply the same changes to `release/3.0` branch

**Comment by dagood** [comment]
> After this is signed off I'll apply the same changes to `release/3.0` branch

Is this necessary? I think we'd just wait until the next preview for a merge. @mmitche

**Comment by jcagme** [comment]
> > After this is signed off I'll apply the same changes to `release/3.0` branch
> 
> Is this necessary? I think we'd just wait until the next preview for a merge. @mmitche

If we don't apply it to release/3.0 then it could be blocking everyone the same as master does. Actually, in my description, the first one is a release/3.0 build which blocked the second one with the new version. If we are not taking changes in release branches I'm ok with waiting

**Comment by dagood** [comment]
> If we don't apply it to release/3.0 then it could be blocking everyone the same as master does. Actually, in my description, the first one is a release/3.0 build which blocked the second one with the new version. If we are not taking changes in release branches I'm ok with waiting

@mmitche @wtgodbe PTAL and advise when this should be merged to `release/3.0`. I don't know how risky vs. helpful this is for stabilization.

**Comment by mmitche** [comment]
We may be able to integrate the change...it's such a big improvement that it may be worth taking in 3.0.  We just need to be ready to revert if things go south.

**Comment by jcagme** [comment]
> We may be able to integrate the change...it's such a big improvement that it may be worth taking in 3.0. We just need to be ready to revert if things go south.

We can leave the change in master running for a day as a test, if we see things worked fine and actually showed an improvement I can then do the same change in `release/3.0` which in theory should have the same positive effects. As a plan B, we just go back to the previous version of the feed.

**Comment by mmitche** [comment]
@jcagme If we're going to leave it for a day, then we should just leave it out of 3.0 for P4. The lower stack will likely be stabilized by that point.

**Comment by jcagme** [comment]
https://github.com/dotnet/core-setup/issues/5753 opened to track pending work on `release/3.0`

**Pull request merged**
