### PR TITLE
Update CentOS 6 docker image

### PR DESCRIPTION
**Pull request by janvorli**
The image now contains clang 3.9 with PGO support

### CODE REVIEW

**Comment by janvorli** [comment]
CC: @mikem8361

**Comment by mikem8361** [comment]
I never did get my llvm 3.9 changes into core-setup so the RHEL 7 image hasn't been changed to the Centos 7 one yet and the arm cross image never got into master. 

Could you also make these changes?

diff --git a/buildpipeline/pipeline.json b/buildpipeline/pipeline.json
index 07db339c..9938a11c 100644
--- a/buildpipeline/pipeline.json
+++ b/buildpipeline/pipeline.json
@@ -19,7 +19,7 @@
           "Name": "Core-Setup-Linux-BT",
           "Parameters": {
             "PB_DistroRid": "rhel.7.2-x64",
-            "PB_DockerTag": "rhel7_prereqs_2",
+            "PB_DockerTag": "centos-7-34f1db9-20171620021620",
             "PB_AdditionalBuildArguments":"-PortableBuild=true -strip-symbols",
             "PB_PortableBuild": "true"
           },
@@ -49,7 +49,7 @@
           "Name": "Core-Setup-Linux-Arm-BT",
           "Parameters": {
             "PB_DistroRid": "ubuntu.14.04-arm",
-            "PB_DockerTag": "ubuntu-14.04-cross-0cd4667-20172211042239",
+            "PB_DockerTag": "ubuntu-14.04-cross-0cd4667-20170319080304",
             "PB_TargetArchitecture": "arm",
             "PB_AdditionalBuildArguments":"-TargetArchitecture=arm -DistroRid=linux-arm -DisableCrossgen=true -PortableBuild=true -SkipTests=true -CrossBuild=true -strip-symbols",
             "PB_CrossBuildArgs": "-e ROOTFS_DIR ",
@@ -190,4 +190,4 @@
       ]
     }
   ]
-}

**Comment by janvorli** [comment]
@mikem8361 done (I've put in the new CentOS 7 image, your diff had the old one)

**Comment by mikem8361** [comment]
Yes. Thanks.

**Pull request merged**
