### PR TITLE
re-enable deb publishing

### PR DESCRIPTION
**Pull request by brthor**
@eerhardt @joshfree @piotrpMSFT

### CODE REVIEW

**Comment by eerhardt** [comment]
Is this really all that is needed?  Why was it shut off in the first place?

**Comment by eerhardt** [comment]
Is it because both repos would have been publishing the packages to debian?

**Comment by brthor** [comment]
Let's talk offline. Our dev feed is published to Microsoft.com/net so this has potential impact for preview1 bits

**Comment by brthor** [comment]
see here:
https://github.com/dotnet/cli/issues/2973

**Pull request merged**
