### PR TITLE
Do build in privileged container for Nuget push to work

### PR DESCRIPTION
**Pull request by gkhanna79**

### CODE REVIEW

**Comment by Petermarcu** [comment]
Lgtm

**Comment by gkhanna79** [comment]
@chcosta @eerhardt I tried this change in a private pipeline build that resulted in successful CrossBuild. If green, I will merge this to see how the formal build goes.

**Comment by gkhanna79** [comment]
@dotnet-bot test Ubuntu x64 Release Build please

**Comment by gkhanna79** [comment]
This appears to have fixed the issue - we got a green build post this change (https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=568524&_a=summary).

**Pull request merged**
