### PR TITLE
Remove stub pacakge generation

### PR DESCRIPTION
**Pull request by ellismg**
The stub package generation was from a previous model of the build
where we needed to ensure host packages for all supported platforms
existed when we restored test assets.

We no longer have this dependency, we only ever consume packages from
the current platform we are building, so we can remove all of this
code.

### CODE REVIEW

**Comment by ellismg** [comment]
@gkhanna79 @eerhardt Thoughts?

**Comment by eerhardt** [comment]
@dotnet-bot test this please

I think some new changes came in that might conflict with this change.

**Comment by gkhanna79** [comment]
> We no longer have this dependency

Is this because we switched to RID split version of M.N.App? If not, then I am not sure what makes them redundant?

**Comment by eerhardt** [comment]
We no longer have this dependency because of this change:  https://github.com/dotnet/core-setup/pull/1088

**Comment by gkhanna79** [comment]
Sounds fine, though Test infra requires fixing as well @ellismg.

**Comment by weshaggard** [comment]
LGTM once green.

fyi @chcosta

**Comment by ellismg** [comment]
> Sounds fine, though Test infra requires fixing as well @ellismg.

Whoops!  I had this fixed locally but I must have dropped the commit as part of a rebase.

**Comment by eerhardt** [comment]
@ellismg - are we still interested in making this change?

**Comment by ellismg** [comment]
@eerhardt Whoops, yes, I still want to do this.  I think I've fixed up the test issues but I'm doing a build locally and then I'll update the PR.

**Comment by eerhardt** [comment]
Thanks, @ellismg!

**Pull request merged**
