### PR TITLE
[release/2.1] Enable Tizen CI

### PR DESCRIPTION
**Pull request by gbalykov**
cc @alpencolt

### CODE REVIEW

**Comment by joshfree** [comment]
FYI @leecow on CI change to release/2.1

**Comment by jamshedd** [comment]
Approved for 2.1.6

**Comment by gbalykov** [comment]
@dotnet-bot test ci please

**Comment by gbalykov** [comment]
@dotnet-bot test Tizen armel Release Build

**Comment by gbalykov** [comment]
@dotnet-bot test ci please

**Pull request merged**
