### PR TITLE
Fix Linux badge generation and disable arm build checks

### PR DESCRIPTION
**Pull request by gkhanna79**
@schellap PTAL

Since Pipeline build does not yet do Linux Arm builds, I have disabled checking for them as they resulted in messages like the ones below (see in https://mseng.visualstudio.com/DefaultCollection/dotnetcore/_build?_a=summary&buildId=3520833):

```
2016-12-28T20:11:58.7894422Z Not all builds complete, badge not found: sharedfx_Ubuntu_14_04_arm
2016-12-28T20:11:58.7894422Z Not all builds complete, badge not found: sharedfx_Ubuntu_16_04_arm
```

These were introduced as part of the Linux Arm32 change on 12/19 and since then, the Azure blob storage didnt get latest builds published to them even though pipeline build was clean.

### CODE REVIEW

**Comment by gkhanna79** [comment]
Merging to get a build out today.

@wtgodbe Please share the link to the build once it is triggered.

**Comment by wtgodbe** [comment]
https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build/explorer?_a=summary&buildId=492715

**Comment by schellap** [comment]
LGTM.

**Comment by wtgodbe** [comment]
Build succeeded, did you get badges?

**Comment by gkhanna79** [comment]
Yes, got them and the readme.md is also updated as expected.

**Pull request merged**
