### PR TITLE
Update dotnet/versions/dotnet/core-setup when the build finalizes.

### PR DESCRIPTION
**Pull request by eerhardt**
@brthor

### CODE REVIEW

**Comment by brthor** [comment]
Why close it?

**Comment by eerhardt** [comment]
It's broke right now.  I'm updating it and will re-open.

**Comment by eerhardt** [comment]
I will squash this together when I merge (if the changes are acceptable).

**Comment by brthor** [comment]
Looks good :shipit:

**Comment by brthor** [comment]
Env Variables are already on VSO

**Pull request merged**
