### PR TITLE
Enable WinArm32 CI support

### PR DESCRIPTION
**Pull request by gkhanna79**
@mmitche @ianhays PTAL

### CODE REVIEW

**Comment by gkhanna79** [comment]
@dotnet-bot test ci please

**Comment by ianhays** [comment]
Won't putting arm in the same job definition as the other platforms make Jenkins expect xunit results?

**Comment by gkhanna79** [comment]
You are right - I think I should skip the following for Arm:

https://github.com/dotnet/core-setup/pull/532/files#diff-2d212ad84506951c8f928e21aed24580R65

What do you think?

**Comment by gkhanna79** [comment]
@dotnet-bot test this please

**Comment by gkhanna79** [comment]
@dotnet-bot test ci please

**Comment by ianhays** [comment]
Looks good.

Also, do we want this trigger-able on every PR? That's what

```
     Utilities.addGithubPRTriggerForBranch(newJob, branch, "${os} ${architecture} ${configuration} Build")
```
does.

**Comment by gkhanna79** [comment]
@ianhays Yes, we want it per PR.

**Comment by gkhanna79** [comment]
@mmitche Do we not have Windows SDK installed on the CI machines used for Core-Setup repo? I see the following error in https://ci.dot.net/job/dotnet_core-setup/job/master/job/GenPRTest/job/debug_windows_nt_arm_prtest/3/consoleFull: 

```
14:37:42 CMake Error at cli/setup.cmake:93 (message):
14:37:42   Windows SDK is required for the Arm32 build.
14:37:42 Call Stack (most recent call first):
14:37:42   cli/exe/CMakeLists.txt:15 (include)
```

**Comment by ianhays** [comment]
Cool, LGTM then.

Gaurav, your issue might be from not calling vcvarsall. Check out https://github.com/dotnet/core-setup/blob/eca152525e19a41d489cd5845afa14982653cc0a/build.cmd

**Comment by gkhanna79** [comment]
@ianhays I dont do that even on my dev machine and it just works. We dont do that even for x86 and x64.

**Comment by mmitche** [comment]
@gkhanna79 Any idea what Windows SDK it's looking for?  On the machine this is the contents of:

C:\Program Files (x86)\Microsoft SDKs\Windows

v10.0A
v7.0A
v7.1A
v8.0
v8.0A
v8.1
v8.1A

**Comment by gkhanna79** [comment]
@mmitche Windows SDK is installed under `PF (x86)\Windows Kits\`. There should be a "10" under that folder. Does that exist?

**Comment by gkhanna79** [comment]
And if it exists, then what are its contents?

**Comment by mmitche** [comment]
Exists, and bin directories contains arm, arm64, x86, x64, etc.

**Comment by gkhanna79** [comment]
@ianhays PTAL at the change to invoke vcvarsall.

**Comment by gkhanna79** [comment]
@dotnet-bot test ci please

**Comment by gkhanna79** [comment]
@mmitche This change still failed (see https://ci.dot.net/job/dotnet_core-setup/job/master/job/GenPRTest/job/debug_windows_nt_arm_prtest/11/consoleFull). Can you please get me one of these machines offline so that I can take a look at what's happening?

**Comment by gkhanna79** [comment]
@dotnet-bot test ci please

**Comment by gkhanna79** [comment]
@dotnet-bot test ci please

**Comment by gkhanna79** [comment]
@dotnet-bot test this please

**Pull request merged**
