### PR TITLE
Mark M.NC.App 1.0.1 stable

### PR DESCRIPTION
**Pull request by weshaggard**
cc @ericstj @eerhardt @gkhanna79

### CODE REVIEW

**Comment by gkhanna79** [comment]
Lgtm

**Comment by gkhanna79** [comment]
Why do the legs fail though?

**Comment by weshaggard** [comment]
Do we need new host packages? The host packages are still marked as prerelease in this branch which is why the CI is failing.

**Comment by weshaggard** [comment]
I've updated the PR to mark the Host packages as stable as they already shipped stable and filtered the package built to just Microsoft.NETCore.App which should align with what we are wanting here.

**Comment by gkhanna79** [comment]
> mark the Host packages as stable as they already shipped stable and filtered the package built to just Microsoft.NETCore.App which should align with what we are wanting here.

Sounds good to me. Also lines up with our approach for servicing packages as discussed.

CC @schellap

**Comment by weshaggard** [comment]
unfortunately this still breaks stuff because the core-setup repo relies on all the packages being their or it fails. I'm still working on getting this updated.

**Pull request merged**
