### PR TITLE
Update 1.0.* servicing to 1.0.4

### PR DESCRIPTION
**Pull request by schellap**
@gkhanna79 PTAL.

I will pick up your dependencies in a follow-up commit.

There is no project.json corresponding to: https://github.com/dotnet/core-setup/pull/727/files

### CODE REVIEW

**Comment by gkhanna79** [comment]
LGTM. Looks like the PlatformAbstractions and related assemblies came in post RTM in https://github.com/dotnet/core-setup/commit/6c3fd24f46daf4766ba152338440ffea4b6ac828#diff-e888dd7228fc4c1a34cff8827e2a3054.

**Comment by gkhanna79** [comment]
Can you please update the CoreCLR and JIT package versions in DependencyVersions.cs as well?

**Comment by schellap** [comment]
@dagood, is it intentional that `Microsoft.NETCore.Platforms` is missing here: https://github.com/dotnet/versions/blob/master/build-info/dotnet/corefx/release/1.0.0/Latest_Packages.txt

It has been present in the other versions in `git log`.

**Comment by schellap** [comment]
@mellinoe can you help answer the above qn?

**Comment by gkhanna79** [comment]
I would think that is expected since there are no new packages produced from CoreFX (since none changed).

@ericstj to chime in as well.

**Comment by dagood** [comment]
Yes, the meaning is that no `Microsoft.NETCore.Platforms` is planned to ship from CoreFX yet. I'm making changes to support that, e.g. https://github.com/dotnet/core-setup/pull/793.

**Comment by schellap** [comment]
@dotnet-bot test Ubuntu x64 Release Build please

**Comment by gkhanna79** [comment]
@dagood Now that this is merged, do you want to force another Maestro update of CoreFX into Core-setup without doing a CoreFX pipeline build to confirm all looks good?

**Comment by dagood** [comment]
Sure, merged https://github.com/dotnet/core-setup/pull/793 (which didn't include package upgrade) and I'll shortly queue an auto-PR build manually.

**Comment by gkhanna79** [comment]
Thanks @dagood. Once that is green, I will send email about branches being open.

**Pull request merged**
