### PR TITLE
change release monikers for 1.0.0 (release/1.0.0)

### PR DESCRIPTION
**Pull request by brthor**
Update monikers for the installers.

asdfasdfasdf

### CODE REVIEW

**Comment by brthor** [comment]
myget is down

**Comment by brthor** [comment]
@dotnet-bot test this please

**Comment by eerhardt** [comment]
:shipit: when green

**Comment by brthor** [comment]
@dotnet-bot test this please

**Comment by brthor** [comment]
Fixed in HostFXR PR

**Pull request closed without merging**
