### PR TITLE
Remove unused code and fix error message

### PR DESCRIPTION
**Pull request by schellap**
@brthor PTAL. Testing VSO definition as well with this change in master.

### CODE REVIEW

**Comment by brthor** [comment]
Nice! We've got an issue here, @mellinoe made a fix in release/1.0.0 you can quickly make it in master as well

projects under `test` need to target Microsoft.NETCore.App `1.0.0` since that's what the sdk brings

projects under `TestAssets` need to target `1.1.0-*` since that's what we're building

**Comment by mellinoe** [comment]
There is also a project under tools/dotnet-deb-tool which needs updating.

**Comment by brthor** [comment]
good point @mellinoe , `dotnet-deb-tool` can reference `1.0.0` it has no need for the latest here.

**Comment by schellap** [comment]
>  @mellinoe made a fix in release/1.0.0 
@mellinoe is there a commit you have?

**Comment by brthor** [comment]
> @mellinoe is there a commit you have?

Even if you take the commit ensure TestAssets are targeted differently than they are on release/1.0.0

**Comment by mellinoe** [comment]
It's this commit: https://github.com/dotnet/core-setup/commit/d7b37f34cbe759821db61cb724037187886094d6

**Comment by schellap** [comment]
@dotnet-bot test this please

**Pull request merged**
