### PR TITLE
Enable Tizen CI

### PR DESCRIPTION
**Pull request by gbalykov**
cc @alpencolt

### CODE REVIEW

**Comment by gbalykov** [comment]
@joshfree 

this should start to work now, I'll rebase it and restart ci

**Comment by gbalykov** [comment]
@dotnet-bot test this please

**Comment by gbalykov** [comment]
@joshfree

what is the proper way to restart ci with this PR? `@dotnet-bot test this please` doesn't seem to work

**Comment by mmitche** [comment]
@dotnet-bot test ci please

**Comment by gbalykov** [comment]
@mmitche is there a way to run tizen tests on this PR?

**Comment by mmitche** [comment]
@dotnet-bot test ci please

**Comment by gbalykov** [comment]
@mmitche I see `GeneratedJob{name='release_tizen_armel_prtest'}` in log of `Gen CI(dotnet-ci) - master/netci.groovy`, however, tizen ci job is not started

**Comment by mmitche** [comment]
It doesn't get started automatically, I'll enable it manually.

**Comment by mmitche** [comment]
@dotnet-bot test Tizen armel Release Build

**Comment by gbalykov** [comment]
@mmitche thank you!

**Comment by mmitche** [comment]
@dotnet-bot test Tizen armel Release Build

**Comment by gbalykov** [comment]
@janvorli @joshfree tizen tests have successfully passed

**Comment by joshfree** [comment]
Thanks @gbalykov.  Let's merge this and just monitor the next CI job or two after this to ensure things are still going smoothly with the new leg added.

**Comment by gbalykov** [comment]
@joshfree yes, thank you

**Pull request merged**
