### PR TITLE
replace variables in debian config appropriately

### LINKED ISSUE #161: Debian Package Variable substitution incorrect
Did manual deb verification post-publishing. 

## Steps to reproduce
install 1.0.0 package
apt-cache search dotnet-sharedframework-1.0.0

See 
```
dotnet-sharedframework-microsoft.netcore.app-1.0.0 - %SHARED_FRAMEWORK_BRAND_NAME% %SHARED_FRAMEWORK_NUGET_NAME% etc....
```

## Expected  behavior
variables are replaced.

Fix incoming, we will need to delete the current packages on the feed (sharedfx, hostfxr, host) packages before spinning a new build. 

This is causing dependency versions to be set up incorrectly as well.

This went undetected because it's an issue that didn't trigger test failures as the packages are technically still sound, and publishing has been disabled for some time. 

cc @piotrpMSFT @eerhardt

### PR DESCRIPTION
**Pull request by brthor**
Fixes #161 

Need to delete currently available 1.0.0 packages before merging this.

### CODE REVIEW

**Comment by brthor** [comment]
Edit: won't need to delete packages, confirmed with repo provider, they'll be overwritten

**Comment by brthor** [comment]
@eerhardt  please review

**Comment by eerhardt** [comment]
:shipit:

**Comment by brthor** [comment]
making additional fixes here

**Comment by eerhardt** [comment]
I'm no Debian package expert or even novice by any means.  Do we have someone else that knows about deb packages?

**Comment by brthor** [comment]
@ellismg PTAL

**Comment by brthor** [comment]
I've verified these changes set dependencies appropriately in the entire chain, and all variables are replaced in descriptions. Will post screenshots.

Additionally verified HostFXR SxS by generating a 1.0.2 package

**Comment by ellismg** [comment]
LGTM.  Thanks!

**Comment by brthor** [comment]
Ran into issues testing these properly, ended up needing to extract control files from the deb packages, here are results.

screen shot 2016-06-13 at 5 04 44 pm
screen shot 2016-06-13 at 5 05 17 pm
screen shot 2016-06-13 at 5 06 40 pm

**Comment by schellap** [comment]
@brthor does the CLI require any corresponding changes?

**Comment by brthor** [comment]
No it should not

I am testing my current pr though before merging it.

**Pull request merged**
