### PR TITLE
Update BuildTools

### PR DESCRIPTION
**Pull request by ellismg**

### CODE REVIEW

**Comment by ellismg** [comment]
test Windows_NT x64 Release Build please
test Windows_NT x64 Debug Build please

NuGet issues during restore.

**Comment by ellismg** [comment]
test Windows_NT x64 Release Build please
test Windows_NT x64 Debug Build please

NuGet issues during restore.

**Comment by ellismg** [comment]
test Windows_NT x86 Debug Build please

**Comment by chcosta** [comment]
I'm completely fine pulling in your change to my (just submitted) PR, or resolving the conflict if you want to merge your PR.  https://github.com/dotnet/core-setup/pull/2625

**Comment by weshaggard** [comment]
For my information why are we pulling in _.pdb locally as opposed to from the buildtools package?

**Comment by chcosta** [comment]
There's no "_.pdb" in the buildtools package.  There's a "_._".  If "_.pdb" gets added (added back?) to buildtools, then I think the preference would be to use that.

**Comment by ellismg** [comment]
What @chcosta said is correct.  If we want it to get added to buildtools, I'm happy to do that.

/cc @dagood.

**Comment by weshaggard** [comment]
I think it would be nice for these placeholders to exist there but not necessary. From the change it looked like it was already there which is why I was asking the question.

**Pull request closed without merging**
