### PR TITLE
Add RedHat6 to official builds of core-setup in master branch

### PR DESCRIPTION
**Pull request by smile21prc**
Add RedHat6 to official builds of core-setup in master branch, this is
identical to the PR to enable Rhel6 in release/2.0.0:
https://github.com/dotnet/core-setup/pull/3017

### CODE REVIEW

**Comment by smile21prc** [comment]
Thanks @weshaggard. Yep I'll hold the merge until the bootstrap CLI is available.

**Comment by weshaggard** [comment]
@smile21prc we need to port https://github.com/dotnet/core-setup/commit/15e34cd2c57ae5daa83c412d987dd342886d799a the target moved to https://github.com/dotnet/core-setup/blob/master/dir.targets#L25

**Comment by smile21prc** [comment]
Thanks @weshaggard , ported  15e34cd as suggested.

**Comment by smile21prc** [comment]
@weshaggard . All CI legs fail almost instantly because it couldn't find NuGet.RuntimeModel.dll. Has it been moved/changed to a newer version in master, comparing to release/2.0.0?
1. error MSB3030: Could not copy the file "/src/core-setup/packages/nuget.runtimemodel/3.5.0/lib/netstandard1.3/NuGet.RuntimeModel.dll" because it was not found. [/src/core-setup/build.proj]
2. error MSB3030: Could not copy the file "/mnt/resource/j/workspace/dotnet_core-setup/master/release_linux_x64_prtest/packages/nuget.runtimemodel/3.5.0/lib/netstandard1.3/NuGet.RuntimeModel.dll" because it was not found. [/mnt/resource/j/workspace/dotnet_core-setup/master/release_linux_x64_prtest/build.proj]
3. error MSB3030: Could not copy the file "D:\j\workspace\debug_windows---78d55155\packages/nuget.runtimemodel\3.5.0\lib\net45\NuGet.RuntimeModel.dll" because it was not found. [D:\j\workspace\debug_windows---78d55155\build.proj]

**Comment by weshaggard** [comment]
Looks like the version has changed. https://github.com/dotnet/core-setup/blob/master/tools-local/tasks/core-setup.tasks.csproj#L29.

**Comment by smile21prc** [comment]
Still got the same error after updating the version of nuget.runtimemodel to below:
<CustomTaskDependencies Include="$(PackagesDir)nuget.runtimemodel\4.3.0-preview2-4095\lib\$(NugetModelTFM)\NuGet.RuntimeModel.dll" />

**Comment by smile21prc** [comment]
I built core-setup locally, and didn't see runtimemodel package any more with current version 4.3.0-preview2-4095. It is possible that it might not be needed any longer.

coresetup_packages


Remove it first and verify it all works. If there is still runtime errors then we may need to explicitly add a package reference to it

**Comment by eerhardt** [comment]
@smile21prc - Can you explain why you used the Linux-ARM build template to build for RHEL.6-x64?  I think the ARM build definition should only be used when actually building for ARM architectures.

**Comment by weshaggard** [comment]
This was mirrored from my change I did in the release branch. The ARM template was easier to parameterize a RID specific build from then the Linux template which was all about portable builds and included a bunch of platform specific package builds. I know know the naming is a little weird and I thought about changing it but I didn't go that far.

**Pull request merged**
