### PR TITLE
Remove comhost from shared framework generation. [release/3.0]

### PR DESCRIPTION
**Pull request by jkoritzinsky**
Porting #5255 to release/3.0.

### CODE REVIEW

**Comment by dougbu** [comment]
Now #5255 is in, what's holding this one up?

**Comment by jkoritzinsky** [comment]
I'm confirming if this needs to go through servicing or shiproom.

**Comment by muratg** [comment]
cc @leecow

**Comment by wtgodbe** [comment]
Also CC @mmitche

**Pull request merged**
