### PR TITLE
Misc updates to build system.

### PR DESCRIPTION
**Pull request by ellismg**
This makes it easier for the composed build to flow changes along.

### CODE REVIEW

**Comment by karajas** [comment]
LGTM.

**Comment by ellismg** [comment]
@dotnet-bot test PortableLinux x64 Release Build please

**Comment by ellismg** [comment]
@dotnet-bot test Ubuntu16.04 x64 Release Build please

**Comment by ellismg** [comment]
@dotnet-bot test Ubuntu16.04 x64 Release Build please

**Pull request merged**
