### PR TITLE
Increase bundle's button size: avoid loc clipping

### PR DESCRIPTION
**Pull request by dagood**
Fix button label clipping in Japanese localization. For https://github.com/dotnet/core-setup/issues/6532 and https://github.com/dotnet/core-setup/issues/6679. Fix copied from Core-SDK, https://github.com/dotnet/core-sdk/pull/2123.

Confirmed via `.\dotnet-runtime-5.0.0-dev-win-x64.exe -lang 1041`.

### CODE REVIEW

**Comment by MichaelSimons** [comment]
@dagood - Any chance you could include a screen shot?  Ideally both english and Japanese.  I see you asked on the core-sdk thread but I didn't see a response.  Are there UI design guidelines we should be reviewing?

**Comment by dagood** [comment]
Sure:

| Install | install_en | install_jp |
| --- | --- | --- |
| Uninstall | uninstall_en | uninstall_jp |


> I see you asked on the core-sdk thread but I didn't see a response. Are there UI design guidelines we should be reviewing?

There are the accessibility guidelines (with https://accessibilityinsights.io/docs/en/windows/overview/), but other than that, I'm not aware of any.

**Comment by MichaelSimons** [comment]
My primary concern is using fixed widths and localization never work well together in practice over the long term.

From my days on working on VS Connected Services, I wonder what the VS UX designers would think about this.  My hunch is they would not like the wider buttons.  In VS all wizard buttons like this were supposed to have a 75 pixel min width IIRC.  I have no WiX experience, it looks like they only support fixed width content.  The other feature that I don't see is theme support.  Having to touch this many many places for controls that are supposed to have the same appearance is not ideal.

In the end I have a feeling your proposed/copied changes are the only option in which I have no objection to the changes 😃

**Comment by dagood** [comment]
Everything you're saying is true, and more. Looking forward to ditching the default burn bundle engine.

**Pull request merged**
