### PR TITLE
Update PlatformApis to handle Gentoo Linux.

### PR DESCRIPTION
**Pull request by GurliGebis**
When trying to setup the SDK on Gentoo Linux, the following stack trace it thrown, due to VERSION_ID not being inside /etc/os-release:

> Unhandled Exception: System.TypeInitializationException: The type initializer for 'Microsoft.DotNet.PlatformAbstractions.RuntimeEnvironment' threw an exception. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.DotNet.PlatformAbstractions.Native.PlatformApis.NormalizeDistroInfo(DistroInfo distroInfo)
   at Microsoft.DotNet.PlatformAbstractions.Native.PlatformApis.LoadDistroInfo()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.DotNet.PlatformAbstractions.Native.PlatformApis.GetDistroVersionId()
   at Microsoft.DotNet.PlatformAbstractions.Native.PlatformApis.GetOSVersion()
   at Microsoft.DotNet.PlatformAbstractions.RuntimeEnvironment..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.DotNet.PlatformAbstractions.RuntimeEnvironment.GetRuntimeIdentifier()
   at Microsoft.DotNet.Cli.MulticoreJitProfilePathCalculator.CalculateProfileRootPath()
   at Microsoft.DotNet.Cli.MulticoreJitActivator.StartCliProfileOptimization()
   at Microsoft.DotNet.Cli.MulticoreJitActivator.TryActivateMulticoreJit()
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
Aborted

This fixes issue #2380 , since it checks if we are running in Gentoo Linux, and then just set VersionId to DateTime.Today.ToString("yyyy.MM")

### CODE REVIEW

**Comment by mellinoe** [comment]
A couple of things feel a little odd to me:

* This is specialized to Gentoo, but this problem could potentially occur in other distros as well. I'd prefer a more robust solution to the problem.
* If Gentoo doesn't specify an OS version, then it doesn't seem correct/useful to make one up like this, especially if it will change day-over-day.

Given that this is just a string, I would prefer just returning `string.Empty`, "undefined", or "unavailable" if the information is not available.

**Comment by GurliGebis** [comment]
Good point, I'll refactor it, so it checks if VersionId is null or empty, and then just set it to "unavailable".

**Comment by mellinoe** [comment]
Looking at how other code uses this property, I think it may be better to simply keep the value as `null`. I'm not sure about that, though, so hold off on making more changes until we get a second opinion. @livarcocc @eerhardt Any thoughts on what the best route to take here is?

**Comment by omajid** [comment]
Another question: how does the RID graph handle this? Will `gentoo.unavailable-x64` fall back to generic `linux-x64` or any such thing?

**Comment by mellinoe** [comment]
@omajid Gentoo is not in the RID graph at all -- it won't fall back to anything. You'd need to provide your own runtime.json declaring it's place in the RID graph. I don't know enough about Gentoo to say where it should be.

**Comment by GurliGebis** [comment]
What would it require to get it added to the runtime.json file, once handling of missing VERSION_ID has been sorted out?

**Comment by omajid** [comment]
@GurliGebis just open a PR. [Example](https://github.com/dotnet/corefx/pull/16302).

**Comment by GurliGebis** [comment]
Okay, I'll do that once we this one gets solved :)

**Comment by GurliGebis** [comment]
@mellinoe Is there anything I can do, to help this get fixed? (Would like to get it in before 2.0 is finalized)

**Comment by eerhardt** [comment]
> Looking at how other code uses this property, I think it may be better to simply keep the value as null

I agree.  This value is used to calculate the RID of the current machine.  I don't think we want `gentoo.unavailable-x64` as the RID, do we?  Instead I think we'd want `gentoo-x64`.

Is there some other way to get a version out of a Gentoo installation?  If not, I'd think we just leave the version as blank instead of `unavailable`.

**Comment by omajid** [comment]
> Is there some other way to get a version out of a Gentoo installation?

Gentoo is effectively [versionless](https://en.wikipedia.org/wiki/Gentoo_Linux#Versions). This is also true for some other distributions, such as [Arch Linux](https://en.wikipedia.org/wiki/Arch_Linux#Versions) and OpenSUSE's tumbleweed. [More here](https://www.slant.co/topics/6289/~rolling-release-linux-distributions). These Linux distributions try and include the latest versions of all packages. And each package in these distributions is continuously updated to the latest version.

**Comment by GurliGebis** [comment]
@eerhardt I agree that just having gentoo-x64 would be the best solution, since it, as @omajid mentions does not have versions as such.

The problem is just that currently, it does not handle VersionId being null very well.
When you say blank, do you mean String.Empty or null?

If you mean null, then there need to be some other changes to handle that, since it currently fails here (and most likely some other places) - if you mean String.Empty, I'll submit another patch that handles if VersionId is null, and then just set it to String.Empty - would that be okay?

**Comment by eerhardt** [comment]
My general philosophy is to write policy/logic that handles `null` and `String.Empty` the same way.

Yes, I technically meant `null`.

I think the necessary changes would be:

1. In the place you are currently changing, checking for IsNullOrEmpty and don't do the IndexOf logic.
1. Changing https://github.com/dotnet/core-setup/blob/6887ab556bc8302390782711dcdd75b75e769cf5/src/managed/Microsoft.DotNet.PlatformAbstractions/RuntimeEnvironment.cs#L55 to not prepend a `.` when the OperatingSystemVersion is null or empty.

**Comment by GurliGebis** [comment]
I changed it to set the minorVersionNumberSeparatorIndex variable to -1 if VersionId is null, since that makes the code cleaner.

@eerhardt Is the new patch accepable? :)

**Comment by GurliGebis** [comment]
Great, I'll create another pull request to get Gentoo (and Buildroot while I'm at it) added to the RID table :)

**Pull request merged**
