### PR TITLE
Merge master into release/1.1.0

### PR DESCRIPTION
**Pull request by dagood**
This was an easy merge in terms of conflicts: I just picked release/1.1.0's versions, which were later than master dependency versions.

I do get a restore error locally:
```
Errors in C:\git\core-setup\build_projects\dotnet-host-build\project.json
    Unable to resolve 'runtime.opensuse.42.1-x64.Microsoft.NETCore.Runtime.CoreCLR (>= 1.1.0-preview1-24516-01)' for '.NETCoreApp,Version=v1.0 (opensuse.42.1-x64)'.
    Unable to resolve 'runtime.opensuse.42.1-x64.Microsoft.NETCore.Jit (>= 1.1.0-preview1-24516-01)' for '.NETCoreApp,Version=v1.0 (opensuse.42.1-x64)'.
    Unable to resolve 'runtime.ubuntu.16.10-x64.Microsoft.NETCore.Runtime.CoreCLR (>= 1.1.0-preview1-24516-01)' for '.NETCoreApp,Version=v1.0 (ubuntu.16.10-x64)'.
    Unable to resolve 'runtime.ubuntu.16.10-x64.Microsoft.NETCore.Jit (>= 1.1.0-preview1-24516-01)' for '.NETCoreApp,Version=v1.0 (ubuntu.16.10-x64)'.
```

Is it correct to remove the ubuntu.16.10 and opensuse.42.1 runtimes?

@mellinoe @wtgodbe @gkhanna79

### CODE REVIEW

**Comment by dagood** [comment]
(Not merging this in any form until release/1.1.0 stabilizes, but now we know more about implications.)

**Comment by gkhanna79** [comment]
We should hold off merging these until we have a good release/1.1.0.

**Comment by mellinoe** [comment]
@wtgodbe I think the restore issues may be caused by the missing configurations that I mentioned to you earlier today. Do those versions match what is getting produced out of the release/1.1.0 branch? This should be fixable by just adding the configurations into the release/1.1.0 PipeBuild configuration file, and then updating the versions here.

**Comment by wtgodbe** [comment]
@mellinoe I think you're right - I can add those to pipelines.coreclr.release.1.1.0.json right now and queue off a coreclr build, but that would muddy the waters on what 'end to end' means for today. Worst case, we'd have to wait for that to finish before queueing off the 2nd coreFX build today ( @gkhanna79 that would mean waiting probably an extra 20-30 minutes for the 2nd coreFX build, but would also mean we can get this PR merged and get rid of the fedora timeout issues)

**Comment by dagood** [comment]
> but would also mean we can get this PR merged and get rid of the fedora timeout issues

Just a quick clarification: there's another PR that would need to be applied on top, but its just adding `--disable-parallel` to all the restores.

**Comment by gkhanna79** [comment]
@wtgodbe Sounds good to me.

**Comment by wtgodbe** [comment]
OK, already merged the PR & queued a coreCLR pipebuild - https://devdiv.visualstudio.com/DevDiv/_build/explorer?_a=summary&buildId=333429

@dagood, can you put that PR up now/add that change to this one? Or do we need to wait until the coreCLR pipebuild finishes?

**Comment by dagood** [comment]
@wtgodbe We need a package upgrade to fix this merge from master, but I can make a commit on top of this PR with the `--disable-parallel` fix. Then once the coreclr build comes through we can take the auto-PR, put this PR on top of the auto-PR, then cherry-pick the `--disable-parallel` fix.

**Comment by wtgodbe** [comment]
Alright, the OpenSuse 42.1 and Ubuntu 16.10 packages from CoreCLR should be on the myget feed now @dagood @mellinoe

**Comment by mellinoe** [comment]
Yep, I see a new version here: https://dotnet.myget.org/feed/dotnet-core/package/nuget/runtime.opensuse.42.1-x64.Microsoft.NETCore.Runtime.CoreCLR
`1.1.0-preview1-24516-02`

**Comment by mellinoe** [comment]
@dagood What's the status of this? I'm going to be working on some changes in CLI that will need these distros to be building from release/1.1.0 soon.

**Comment by dagood** [comment]
We wanted to hold off until we had a good baseline official build, which we should have now. I'll rebase this and fix conflicts.

**Comment by dagood** [comment]
Pushed a new merge. Conflicts were still straightforward, mostly just versions.

**Comment by dagood** [comment]
@gkhanna79 @wtgodbe does this look ok to merge?

To clarify, this PR now has nothing to do with `--disable-parallel`, and is purely a merge from master for new platforms.

**Comment by wtgodbe** [comment]
Looks good to me!

**Comment by dagood** [comment]
(Waiting for @mellinoe to merge pending shiproom.)

**Comment by dagood** [comment]
Thanks @mellinoe! This merge kicked off https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build/index?buildId=339789.

**Pull request merged**
