### PR TITLE
Enable Portable Native Binaries SharedFX

### PR DESCRIPTION
**Pull request by gkhanna79**
This change enables packaging for SharedFX built from Portable Native Binaries under the RID of Linux-X64.

@schellap @janvorli @ellismg PTAL.

### CODE REVIEW

**Comment by gkhanna79** [comment]
@dotnet-bot test CentOS7.1 x64 Debug Build OSX x64 Release Build RHEL7.2 x64 Release Build  please

**Comment by gkhanna79** [comment]
@dotnet-bot test  OSX x64 Release Build please

**Comment by gkhanna79** [comment]
@dotnet-bot test RHEL7.2 x64 Release Build please

**Comment by gkhanna79** [comment]
@schellap Test issue for OSX fixed. PTAL - I have submitted a rebased PR.

**Comment by gkhanna79** [comment]
@schellap Can you PTAL at this today as I would like to get this through and work with @wtgodbe to enable pipeline build support for this?

**Comment by schellap** [comment]
Other than the couple of comments above, LGTM.

One question, do you have to build the host in any special way for it to be able to use the dynamic linking?

**Comment by gkhanna79** [comment]
@schellap No, the host does not need to be built specially since it does not have the kinds of dependencies that requires specialized dynamic linking. However, if it does need to do in future, we have the right infrastructure to plumb the support through.

Thanks for taking look.

**Pull request merged**
