### PR TITLE
Port build fixes from master to release/2.0.0

### PR DESCRIPTION
**Pull request by eerhardt**
Disable non-portable builds.

Only publish identity packages from a single build leg (windows x64)

@gkhanna79 @weshaggard @Petermarcu

### CODE REVIEW

**Comment by gkhanna79** [comment]
LGTM  - but there are merge conflicts.

**Comment by eerhardt** [comment]
>  but there are merge conflicts.

There weren't when I submitted it.  :)  fixing.

**Comment by gkhanna79** [comment]
Is this ready to merge @eerhardt ?

**Comment by eerhardt** [comment]
yes, just waiting on ship room approval.  /cc @Petermarcu

**Comment by eerhardt** [comment]
Approved over email.  Merging.

**Pull request merged**
