### PR TITLE
Update UWP metapackage to reference latest .NET Core 1.1 Serialization packages

### PR DESCRIPTION
**Pull request by weshaggard**
Addresses https://github.com/dotnet/core-setup/issues/364.

cc @ericstj  @yizhang82 @shmao @mconnew @huanwu

### CODE REVIEW

**Comment by yizhang82** [comment]
@weshaggard Thanks. How do I see the entire closure of the pre-release packages getting pulled in?

**Comment by weshaggard** [comment]
For a diff of the lock file with a private version of this package see https://github.com/weshaggard/corefxlab/commit/c8c6e990137d45dab2b0560e772ce93e5a233a79. Github doesn't show a diff online so you will need to pull the branch and diff to see the delta.

**Comment by ericstj** [comment]
@weshaggard cherry-picking packages is at-odds with the re-baselining that went in to the 1.1 branch.  If you cherry-pick you could cause downgrades (check the restore log for warnings) or you could pull down inconsistent identity/lineup packages (problem if package moves from split to fat, like Reflection.Extensions did in master).  Can you double check for these, ensuring you have the latest corefx build with the baselining change?

**Comment by weshaggard** [comment]
@gkhanna79 are there issues with the linux CI legs? I don't think my changes would have caused any of those failures they look more like some infra issue.

@ericstj I didn't see any downgrade warnings while restoring the new meta-package.

**Comment by gkhanna79** [comment]
```
17:39:21 The specified framework 'Microsoft.NETCore.App', version '1.0.0' was not found.
17:39:21   - Check application dependencies and target a framework version installed at:
17:39:21       /mnt/resource/j/workspace/dotnet_core-setup/master/debug_centos7.1_x64_prtest/.dotnet_stage0/Linux/shared/Microsoft.NETCore.App
17:39:21   - The following versions are installed:
17:39:21       1.0.2-servicing-004528-00
```

This issue was (partially) fixed by @wtgodbe yesterday when fixing https://github.com/dotnet/core-setup/issues/234. You will need to close/reopen the PR (or resubmit) for it to be picked up.

**Pull request merged**
