### PR TITLE
Fixes for Arm32 build

### PR DESCRIPTION
**Pull request by gkhanna79**
Specify CROSS=1 for the cross build.

Ensure that platform installers are not attempted to be published for Arm32.

### CODE REVIEW

**Comment by gkhanna79** [comment]
@eerhardt Can you PTAL?

**Comment by gkhanna79** [comment]
Fixes issues like https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build?_a=summary&buildId=564928

**Comment by eerhardt** [comment]
> Ensure that platform installers are not attempted to be published for Arm32.

Why?  Why don't we publish `apt-get` installers for arm32?

**Comment by gkhanna79** [comment]
The deb generation logic appears to be using x64 tools that do not operate on arm32 binaries. This change is to get things going and then look later into what it means to deb generation for architectures like Arm and Arm64.

**Comment by gkhanna79** [comment]
@eerhardt Let me know if there are any further questions I can help answer.

**Comment by eerhardt** [comment]
As long as we have an issue logged and a plan to get these built, I am happy.

**Pull request merged**
